.stylelintrc.json, package.json, src/application/page1/ReservationUnitList.tsx, src/application/page1/ReservationUnitModal.tsx, src/component/Card.tsx, src/reservation-unit/Head.tsx, src/search/SearchForm.tsx, src/search/SearchResultList.tsx, yarn.lock
- lint css from components
- add support for styled components
- fix existing errors
=> Fix css problems

src/application/page1/ApplicationEvent.tsx, src/application/page1/Page1.tsx, src/application/page1/ReservationUnitList.tsx, src/application/page1/ReservationUnitModal.tsx, src/application/page2/TimeSelector.tsx, src/application/page3/Page3.tsx, src/application/preview/Preview.tsx, src/common/const.ts, src/common/routes.tsx, src/common/style.ts, src/component/Modal.tsx, src/home/ApplicationPeriodCard.tsx, src/home/Home.tsx, src/i18n/messages.ts, src/search/SearchForm.tsx
also fixes 
- breakpoints of media queries
- responsiveness issues on application form inputs
=> TILA-257 dialog interaction refactoring

src/application/Application.tsx, src/application/applicationInitializer.ts, src/application/applicationReducer.ts, src/application/page1/Page1.tsx, src/application/preview/Preview.tsx, src/common/types.ts, src/i18n/messages.ts
- now application initializes without application events and they must be added manually
- also fixes preview page  (terms component was duplicated)
=> TILA-256 refactor start application

e2e/accessibility/testAllPages.ts, e2e/tests/model/search.ts, src/application/page1/ReservationUnitList.tsx, src/application/page1/ReservationUnitModal.tsx, src/application/preview/Preview.tsx, src/common/types.ts, src/common/util.ts, src/i18n/messages.ts, src/index.scss, src/reservation-unit/Address.tsx, src/reservation-unit/ExternalLink.tsx, src/reservation-unit/Head.tsx, src/reservation-unit/ReservationUnit.tsx, src/search/ReservationUnitCard.tsx, src/variables.css
also
- run all axe tests
- specify default font
=> TILA-393 Display address on reservatiion unit page

src/reservation-unit/Head.tsx, src/reservation-unit/Images.tsx, src/reservation-unit/ReservationUnit.tsx
=> Display thumbnail images according to layout

package.json, src/applications/ApplicationCard.tsx, src/applications/Applications.tsx, src/applications/ApplicationsGroup.tsx, src/applications/Head.tsx, src/common/util.ts, src/component/Navigation.tsx, src/component/common.ts, src/home/ApplicationRoundCard.tsx, src/i18n/messages.ts, src/variables.css, yarn.lock
=> TILA-359 own applications

e2e/accessibility/testAllPages.ts, e2e/tests/model/application.ts, e2e/tests/startNewApplication.test.ts, src/application/applicationReducer.ts, src/application/page1/ApplicationEvent.tsx, src/application/page1/ApplicationEventSummary.tsx, src/application/page1/ReservationUnitList.tsx, src/common/const.ts, src/common/types.ts, src/common/util.ts, src/component/ControlledSelect.tsx, src/i18n/messages.ts, src/search/ReservationUnitCard.tsx
Change min & max duration from input to select
=> TILA-494 change duration input

src/application/page1/ApplicationEvent.tsx, src/application/preview/Preview.tsx, src/common/util.ts, src/i18n/messages.ts
also:
- preview page: remove unused content, add duration(min, max)
- do not set state on unmounted component
=> TILA-514 remove unused field from application, preview

admin-ui/src/App.tsx, admin-ui/src/common/api.ts, admin-ui/src/common/types.ts, admin-ui/src/component/Unit/ExternalLink.tsx, admin-ui/src/component/Unit/InfoModalContent.tsx, admin-ui/src/component/Unit/Unit.tsx, admin-ui/src/i18n/messages.ts
Initial implementation for page layout
* uses mock data (no api)
=> TILA-665 initial layout

admin-ui/src/common/auth/axiosClient.ts, admin-ui/src/common/queries.ts, admin-ui/src/common/types.ts, admin-ui/src/component/ConfirmationDialog.tsx, admin-ui/src/component/HDSModal.tsx, admin-ui/src/component/Unit/NewResourceModal.tsx, admin-ui/src/component/Unit/NewSpaceModal.tsx, admin-ui/src/component/Unit/ResourcesTable.tsx, admin-ui/src/component/Unit/SpacesResources.tsx, admin-ui/src/component/Unit/SpacesTable.tsx, admin-ui/src/component/Unit/Unit.tsx, admin-ui/src/component/Unit/Units.tsx, admin-ui/src/i18n/messages.ts
- resource creation dialog
- delete operation for resource and space
=> TILA-675 & TILA-673

admin-ui/src/common/apolloClient.ts, admin-ui/src/common/auth/axiosClient.ts, admin-ui/src/common/auth/util.ts
Send JWT with graphql requests
=> TILA-762 authentication header to graphql requests

admin-ui/src/common/queries.ts, admin-ui/src/component/DataTable.tsx, admin-ui/src/component/ReservationUnits/ReservationUnitsList.tsx, admin-ui/src/component/Resources/ResourcesList.tsx, admin-ui/src/component/Spaces/SpacesList.tsx, admin-ui/src/component/Unit/NewResourceModal.tsx, admin-ui/src/component/Unit/ResourcesTable.tsx, admin-ui/src/component/Unit/SpacesResources.tsx, admin-ui/src/component/Unit/SpacesTable.tsx, admin-ui/src/component/Unit/Unit.tsx, admin-ui/src/i18n/messages.ts
fixed some minor issues with list views
- linking to editor view
- sorting of undefined values
- list data refreshing when new list items created
- minor issues with queries
=> TILA-787 list view fixes

admin-ui/src/common/gql-types.ts, admin-ui/src/component/ReservationUnits/ReservationUnitEditor.tsx
- also make error notification dismissible
=> Fix for duration api changes

admin-ui/src/common/queries.ts, admin-ui/src/component/ReservationUnits/ReservationUnitEditor/index.tsx, admin-ui/src/component/ReservationUnits/ReservationUnitEditor/reducer.ts, admin-ui/src/i18n/messages.ts
Add localized contactinformation field to form (lack of it prevents publishing atm)
=> Add contact information field to form

admin-ui/src/component/DataTable.tsx
=> TILA-1366 allow opening rows to "new tab"

admin-ui/src/common/util.ts, admin-ui/src/component/applications/Applications.tsx, admin-ui/src/component/recurring-reservations/Review.tsx
- filter accepts now or like matches inside single key (group)
=> TILA-1403 change filtering logic

admin-ui/src/common/gql-types.ts, admin-ui/src/component/DataTable.tsx, admin-ui/src/component/reservations/requested/queries.ts
- add prefix to link urls
- update api model
=> Prod fixes

admin-ui/src/common/auth/axiosClient.ts, admin-ui/src/component/applications/Application.tsx, admin-ui/src/component/applications/ApplicationDetails.tsx, admin-ui/src/component/applications/ReservationByApplicationEvent.tsx, admin-ui/src/component/applications/util.ts, admin-ui/src/component/recurring-reservations/Review.tsx, admin-ui/src/component/recurring-reservations/util.tsx, admin-ui/src/context/NotificationContext.tsx
- truncate applicant name
- use applicant name from form data (in listing and also on details page)
=> TILA-1478, TILA-1479

admin-ui/Dockerfile, admin-ui/package.json, common/package.json, package.json, ui/components/application/IndividualForm.tsx, ui/components/form/__tests__/__snapshots__/DateSelectorMenu.test.tsx.snap, ui/components/reservation/__tests__/__snapshots__/Ticket.test.tsx.snap, yarn.lock
some libs (at least @react-pdf/renderer) cannot cope with react 18 types atm.
also:
- format package.json files
- move admin-ui dev deps  in to devDependencies section
- update apollo libs
=> make sure we use react 17 @types

admin-ui/src/common/Error403.tsx, admin-ui/src/component/Navigation.tsx
- hide navigation login state
- fixed logout
=> TILA-1574 fix for no permissions view

ui/cypress/integration/recurring-lander.ts, ui/modules/applicationRound.ts, ui/pages/recurring/index.tsx, yarn.lock
=> TILA-1777 propcheck++

admin-ui/src/component/ReservationUnits/ReservationUnitEditor/reducer.test.ts, admin-ui/src/component/ReservationUnits/ReservationUnitEditor/reducer.ts
fix reservationsMinDaysBefore initialization when reservationsMaxDaysBefore is set
=> TILA-1845 fix value initialization

admin-ui/src/common/urls.ts, admin-ui/src/component/BreadcrumbWrapper.tsx, admin-ui/src/component/DataTable.tsx, admin-ui/src/component/Resources/ResourcesList.tsx, admin-ui/src/component/Spaces/SpacesList.tsx, admin-ui/src/component/Unit/ResourcesTable.tsx, admin-ui/src/component/lists/components.tsx
-use react-router for urls
-fix front page link
=> Fixing urls part 2

admin-ui/src/component/ReservationUnits/ReservationUnitEditor/ActivationGroup.tsx, admin-ui/src/component/ReservationUnits/ReservationUnitEditor/EnumSelect.tsx, admin-ui/src/component/ReservationUnits/ReservationUnitEditor/FieldGroup.tsx, admin-ui/src/component/ReservationUnits/ReservationUnitEditor/ImageEditor.tsx, admin-ui/src/component/ReservationUnits/ReservationUnitEditor/ReservationUnitEditor.tsx, admin-ui/src/component/ReservationUnits/ReservationUnitEditor/Select.tsx, admin-ui/src/component/ReservationUnits/ReservationUnitEditor/modules/reservationUnitEditor.ts, admin-ui/src/component/RichTextInput.tsx, admin-ui/src/i18n/messages.ts, admin-ui/src/index.scss, admin-ui/src/styles/layout.tsx
\+ small text changes & tweaks from TILA-1853 + TILA-1855
=> TILA-1211 tooltips

admin-ui/src/common/PrivateRoutes.tsx, admin-ui/src/component/recurring-reservations/ApplicationRounds.tsx, admin-ui/src/context/AuthStateContext.tsx, admin-ui/src/context/authStateReducer.ts
- move rest of state management to reducer
- fix for access token expired
=> TILA-1907 auth flow fixes

admin-ui/src/component/reservations/requested/Calendar.tsx
calendar now shows current reservation and reservations that have state "confirmed" or "requires handling"
=> TILA-1750 filter displayed reservations

admin-ui/src/component/ReservationUnits/ReservationUnitEditor/reducer.ts
=> TILA-1957 handle unset pricing type 

admin-ui/src/component/reservations/requested/RequestedReservation.tsx, admin-ui/src/component/reservations/requested/UserBirthDate.tsx, admin-ui/src/component/reservations/requested/queries.ts, admin-ui/src/i18n/messages.ts
add users birthdate, name into reservation details view
=> TILA-1918, TILA-1904

common/types/common.ts, ui/README.md, ui/components/reservation-unit/ReservationUnitList.tsx, ui/modules/api.ts, ui/modules/apolloClient.ts, ui/modules/auth/axiosClient.ts, ui/modules/auth/util.ts, ui/modules/const.ts, ui/next.config.js
also 
- cleaned up some old unused rest api surface
- removed authlink from serverside api calls
=> TILA-2016 pass profile jwt to backend with api calls

admin-ui/src/component/reservations/queries.ts
=> TILA-1863 cleanup

admin-ui/src/common/gql-types.ts, admin-ui/src/component/reservations/Filters.tsx, admin-ui/src/component/reservations/PaymentStatusFilter.tsx, admin-ui/src/component/reservations/ReservationsDataLoader.tsx, admin-ui/src/component/reservations/ReservationsTable.tsx, admin-ui/src/component/reservations/queries.ts, admin-ui/src/component/reservations/requested/ApproveDialog.tsx, admin-ui/src/component/reservations/requested/RequestedReservation.tsx, admin-ui/src/component/reservations/requested/queries.ts, admin-ui/src/i18n/messages.ts, tilavaraus.graphql
Display reservation payment status on listing views & reservation details view
=> TILA-2031 Display reservation payment status

ui/components/common/TermsBox.tsx, ui/components/reservation/Step1.tsx, ui/cypress/integration/reservation-unit.ts, ui/cypress/model/notification.ts, ui/pages/reservation-unit/[...params].tsx, ui/pages/terms/general/index.tsx, ui/public/locales/en/reservationCalendar.json, ui/public/locales/fi/reservationCalendar.json, ui/public/locales/sv/reservationCalendar.json
Replace terms-of-service -elements in reservation funnel.
=> TILA-2052 reservation funnel terms

admin-ui/src/component/my-units/UnitCalendar.tsx
- Adds a title into calendar event
=> TILA-2122: Adds title into the calendar event

admin-ui/src/component/my-units/UnitCalendar.tsx, admin-ui/src/component/my-units/UnitReservations.tsx, admin-ui/src/component/my-units/const.ts, admin-ui/src/component/my-units/queries.ts
- Updates the "ordered resources" table to show status via border-color
=> Tila 2114: Show the status of ordered resources

admin-ui/src/component/my-units/UnitCalendar.tsx
- Fixes events going over resources in resource calendar (zindex bug)
- Adds missing key: params to calendar event buffers
=> TILA-2153: Event z-index bug

tilavaraus.graphql, ui/components/reservation/ReservationCard.tsx, ui/components/reservation/ReservationOrderStatus.tsx, ui/components/reservation/ReservationStatus.tsx, ui/components/reservation/__tests__/ReservationOrderStatus.test.tsx, ui/components/reservation/__tests__/ReservationStatus.test.tsx, ui/cypress/integration/reservations.ts, ui/mocks/handlers/reservation.ts, ui/modules/__tests__/reservation.test.ts, ui/modules/reservation.ts, ui/pages/reservations/index.tsx, ui/public/locales/en/reservations.json, ui/public/locales/fi/reservations.json, ui/public/locales/sv/reservations.json
Display reservation order status only within certain reservation states.
=> TILA-2116 reservation order state changes

admin-ui/src/common/hooks.ts, admin-ui/src/component/Tabs.tsx, admin-ui/src/component/my-units/DayNavigation.tsx, admin-ui/src/component/my-units/MyUnitView.tsx, admin-ui/src/component/my-units/UnitReservationsView.tsx
- Adds datepicker option for reservation calendar
- Adds url parametrization for date and tab to reservation calendar
=> Tila 2161: Adding datepicker to reservation calendar

ui/modules/__tests__/reservation.test.ts
=> TILA-2191 fix tests

admin-ui/src/component/BirthDate.tsx, admin-ui/src/component/ReservationUnits/ReservationUnitEditor/DateTimeInput.tsx, admin-ui/src/component/ReservationUnits/ReservationUnitEditor/ReservationUnitEditor.tsx, admin-ui/src/component/ReservationUnits/ReservationUnitEditor/reducer.ts, admin-ui/src/component/my-units/UnitReservations.tsx, admin-ui/src/component/recurring-reservations/AllApplicationRounds.tsx, admin-ui/src/component/recurring-reservations/util.tsx, admin-ui/src/component/reservations/requested/ApproveDialog.tsx, admin-ui/src/component/reservations/requested/Calendar.tsx, admin-ui/src/component/reservations/requested/util.test.ts, admin-ui/src/component/reservations/requested/util.ts, common/codegen.yml, common/package.json, common/src/calendar/util.ts, common/src/termsbox/__tests__/TermsBox.test.tsx, common/types/gql-types.ts, ui/components/Carousel.tsx, ui/components/calendar/ReservationCalendarControls.tsx, ui/components/reservation-unit/QuickReservation.tsx, ui/components/reservation/EditStep0.tsx, ui/components/reservation/ReservationInfoCard.tsx, ui/mocks/handlers/reservationUnit.ts, ui/modules/__tests__/reservation.test.ts, ui/modules/__tests__/reservationUnit.test.ts, ui/modules/reservation.ts, ui/modules/reservationUnit.ts, ui/pages/reservation-unit/[id].tsx
- Updates graphql-codegen scalar types to limit the amount of 'any' typings
- 'Fixes' ts-check errors in ui and admin-ui
- 'Fixes' Carousel component
=> Tila 2118 - GraphQL updated scalar typedefinition

ui/components/reservation-unit/QuickReservation.tsx, ui/pages/reservation-unit/[id].tsx
- Fixes error with reservation unit page buffertime before / after
- Replaces "javascript:void(0)" behaviour in calendarlink
=> Tila 2207 - Reservation unit page fix

ui/components/calendar/Toolbar.tsx
- Fixes date formatting in calendar toolbar
=> TILA-2120: Fixes date formatting in calendar toolbar

admin-ui/src/component/ReservationUnits/ReservationUnitEditor/ReservationUnitEditor.tsx
- Updates 'pricingterms' to be shown only if the reservation status is not free.
=> Checking for 'isPaid' when showing pricingTerms

admin-ui/azure-pipelines.yml, ui/azure-pipelines.yml
Allow pipelines to trigger build without all previous build finished
=> modify ci-pipeline trigger config

admin-ui/src/component/reservations/requested/ApproveDialog.tsx, admin-ui/src/component/reservations/requested/RequestedReservation.tsx
Block user from changing price in modal if the reservation unit is free of charge.
=> TILA-1956: Fix turning free reservations into paid

ui/public/locales/sv/reservationCalendar.json
Added translation for reservationQuotaLabel
=> TILA-2184/1848 Translations missing

admin-ui/src/component/lists/More.tsx, admin-ui/src/component/reservations/ReservationsDataLoader.tsx, admin-ui/src/component/reservations/requested/RecurringReservationsView.tsx, admin-ui/src/component/reservations/requested/RequestedReservation.tsx, admin-ui/src/component/reservations/requested/queries.ts
Fix: don't block load more button by default
Fix: end time
Fix: Load more than 100 linked reservations for recurring list
=> TILA-2388: Recurring review fixes

ui/middleware.ts, ui/pages/applications.tsx, ui/pages/reservations/[...params].tsx, ui/pages/reservations/[id].tsx, ui/pages/reservations/index.tsx
The correct way to use protected routes would be configuring next middleware correctly - I'll dig into that after release.
=> TILA-2509 automatic login for certain routes

ui/public/locales/en/reservationList.json, ui/public/locales/en/reservationUnit.json, ui/public/locales/en/reservations.json, ui/public/locales/sv/reservationApplication.json, ui/public/locales/sv/reservationList.json, ui/public/locales/sv/reservationUnit.json
Removed unnecessary "booking" word
=> TILA-2079 translation modifications

ui/components/reservation-unit/Address.tsx
Update HSL-link, fallback to finnish address strings and require street address in link generation.
=> TILA-2604 update hsl link

admin-ui/src/component/my-units/BufferToggles.tsx, admin-ui/src/component/my-units/MetadataSetForm.tsx, admin-ui/src/component/my-units/MyUnitRecurringReservation/commonStyling.tsx, admin-ui/src/component/my-units/ReservationTypeForm.tsx, admin-ui/src/i18n/locales/fi/reservationApplication.json, common/src/reservation-form/MetaFields.tsx
- Fix: Incorrect check in when rendering toggles
- Add at label / title for the toggles
- Some styling fixes to match the design
=> TILA-2625: fix buffer toggle selection

admin-ui/src/component/my-units/create-reservation/CreateReservationModal.tsx, admin-ui/src/component/reservations/EditTimeModal.tsx, admin-ui/src/component/reservations/fragments.ts, admin-ui/src/component/reservations/requested/hooks/index.ts, admin-ui/src/component/reservations/requested/hooks/queries.ts, admin-ui/src/component/reservations/requested/hooks/useCheckCollisions.ts, admin-ui/src/i18n/messages.ts
When reservation is created / changed check against existing reservations and include the buffers if any in those checks.
=> TILA-2626: Add buffer collision checks to reservation time

admin-ui/src/common/api.ts, admin-ui/src/common/queries.ts, admin-ui/src/common/types.ts, admin-ui/src/component/recurring-reservations/Allocation.tsx, admin-ui/src/component/recurring-reservations/ApplicationRound.tsx, admin-ui/src/component/recurring-reservations/Handling.tsx, common/types/common.ts, common/types/gql-types.ts, tilavaraus.graphql, ui/mocks/handlers/reservationUnit.ts, ui/modules/api.ts
Backend refs:
https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/897
https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/898
https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/899
=> TILA-2696: remove code that backend cleaned up

admin-ui/src/component/ReservationsList.tsx, admin-ui/src/component/my-units/MyUnitRecurringReservation/MyUnitRecurringReservationForm.tsx, admin-ui/src/component/my-units/MyUnitRecurringReservation/hooks.ts, admin-ui/src/component/my-units/MyUnitRecurringReservation/queries.ts
When creating a recurring reservation check both the selected and the existing reservation buffers.
=> TILA-2597: Check recurring list against buffers

admin-ui/src/component/my-units/hooks/index.ts
=> TILA-2721: include other reservation in calendar

admin-ui/src/component/my-units/create-reservation/CreateReservationModal.tsx
=> TILA-2595: fix: default to checking against blocked rules

admin-ui/src/component/reservations/hooks/__test__/mocks.ts, admin-ui/src/component/reservations/requested/RequestedReservation.tsx, admin-ui/src/component/reservations/requested/hooks/queries.ts, admin-ui/src/i18n/messages.ts, common/types/gql-types.ts, tilavaraus.graphql, ui/mocks/handlers/reservation.ts
=> TILA-2755: show reservation cancel reason

admin-ui/src/component/reservations/requested/RequestedReservation.tsx, admin-ui/src/component/reservations/requested/hooks/queries.ts, admin-ui/stylelint.config.js, common/types/gql-types.ts, tilavaraus.graphql
Show the cancel / deny reason from the select, not the open comment field.
Refs 2755, 2403
=> TILA-2755/show deny reason in summary

admin-ui/src/component/applications/ApplicationDetails.tsx, admin-ui/src/component/recurring-reservations/allocation/ApplicationEventCard.tsx, admin-ui/src/component/recurring-reservations/review/ApplicationEventsTable.tsx
Refs
TILA-2737: application id
TILA-2658: add anchor links to application events
=> TILA-2737: show application id in the title

admin-ui/src/pages/api/auth/[...nextauth].ts, ui/pages/api/auth/[...nextauth].ts
Remove most of unused profile variables from cookies.
=> TILA-2535: fix: smaller next-auth cookies

apps/ui/components/common/Navigation/NavigationUserMenu/NavigationUserMenu.tsx, apps/ui/pages/reservation-unit/[id].tsx
Two small fixes guarding against `undefined`/`null` references
REF: [TILA-2838](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2838)
[TILA-2838]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix session timeout crash

apps/admin-ui/src/component/notifications/page.tsx
- Remove an extra bracket from JSX.
- Delete single notification caches after edit.
=> TILA-1585: fix remove extra bracket

apps/admin-ui/package.json, apps/admin-ui/src/common/api.ts, apps/admin-ui/src/common/apolloClient.ts, apps/ui/components/reservation-unit/ReservationUnitList.tsx, apps/ui/modules/api.ts, apps/ui/modules/apolloClient.ts, apps/ui/package.json, apps/ui/pages/_app.tsx, apps/ui/pages/application/[...params].tsx, apps/ui/pages/criteria/[id].tsx, apps/ui/pages/index.tsx, apps/ui/pages/recurring/index.tsx, apps/ui/pages/reservation-unit/[...params].tsx, apps/ui/pages/reservation-unit/[id].tsx, apps/ui/pages/reservations/[id].tsx, apps/ui/pages/search/index.tsx, apps/ui/pages/terms/general/index.tsx, pnpm-lock.yaml
Fix: missing CSRF token in REST requests caused mutations not to work.
Add: CSRF token to GRAPQHL requests so backend can enable it.
=> TILA-2723: fix: missing csrf token

apps/ui/components/reservation/ReservationInfoCard.tsx
=> fix: eat the apple (remove typoed -character)

.github/workflows/pipeline.yml, apps/admin-ui/src/component/GlobalElements.tsx, apps/admin-ui/src/component/recurring-reservations/allocation/ApplicationEventScheduleCard.tsx, packages/common/package.json, packages/common/tsconfig.tscheck.json
Only admin and common for now, because types are broken in ui.
=> Add: typecheck action to pipeline

apps/admin-ui/src/component/PageWrapper.tsx, apps/admin-ui/src/component/notifications/page.tsx, apps/ui/components/common/PageWrapper.tsx, packages/common/src/components/BannerNotificationsList.tsx, packages/common/src/components/BannerNotificationsQuery.ts
fix: only query the target we are in (staff / user)
fix: default time values as specced
=> fix: only show banner notifications to target app

apps/ui/components/LoginFragment.tsx, apps/ui/hooks/auth/index.ts, apps/ui/hooks/reservation.tsx, apps/ui/modules/apolloClient.ts, apps/ui/modules/protectedRoute.ts, apps/ui/modules/reservation.ts, apps/ui/modules/util.ts, apps/ui/pages/application/[...params].tsx, apps/ui/pages/applications.tsx, apps/ui/pages/applications/[...params].tsx, apps/ui/pages/applications/[applicationId].tsx, apps/ui/pages/intro.tsx, apps/ui/pages/reservation/cancel.tsx, apps/ui/pages/reservation/confirmation/[id].tsx, apps/ui/pages/reservations/[...params].tsx, apps/ui/pages/reservations/[id].tsx, apps/ui/pages/reservations/index.tsx, apps/ui/pages/success.tsx, apps/ui/public/locales/en/errors.json, apps/ui/public/locales/fi/errors.json, apps/ui/public/locales/sv/errors.json, packages/common/src/components/BannerNotificationsList.tsx
Routes that require user to be logged in are redirected to login page on server side.
=> TILA-2869: fix (ui): redirect on protected routes

apps/admin-ui/src/component/ReservationUnits/ReservationUnitEditor/ReservationUnitEditor.tsx
=> fix: admin allow saving with past pricing

packages/common/src/components/BannerNotificationsList.tsx, packages/common/src/components/BannerNotificationsQuery.ts
=> fix: missing all target when showing notifications

apps/ui/components/application/Head.tsx, apps/ui/components/applications/Head.tsx, apps/ui/components/common/KorosDefault.tsx, apps/ui/pages/_document.tsx, apps/ui/pages/criteria/[id].tsx, apps/ui/pages/index.tsx, apps/ui/pages/recurring/index.tsx
Incorrect use of variables broke the SSR style sheet generation.
=> fix (ui): Koros styled component broke stylesheet

apps/admin-ui/src/component/recurring-reservations/allocation/ApplicationEventCard.tsx, apps/admin-ui/src/component/recurring-reservations/allocation/ApplicationEventScheduleCard.tsx, apps/admin-ui/src/component/recurring-reservations/allocation/ApplicationEvents.tsx, apps/admin-ui/src/component/recurring-reservations/allocation/ApplicationRoundAllocationActions.tsx, apps/admin-ui/src/component/recurring-reservations/allocation/modules/applicationRoundAllocation.ts
Fix: show organisation name if applicable
Refactor: remove useMemo and unnecessary div
Refs: TILA-2829
=> fix applicant name

apps/admin-ui/src/component/applications/queries.ts, apps/admin-ui/src/component/recurring-reservations/ApplicationRound.tsx, apps/admin-ui/src/component/recurring-reservations/review/Review.tsx
fix: missing application creator email field
fix: incorrect breadcrumb link
refactor: move breadcrumb to page
Refs: TILA-2840
=> Fix application creator email

apps/ui/components/search/ReservationUnitCard.tsx
=> fix: add locale to search result href

apps/ui/components/single-search/FilterTagList.tsx
Use array filter method instead of lodash-omit
=> Fix empty-button not showing with the filter tags

apps/ui/modules/const.ts, apps/ui/pages/reservation-unit/[id].tsx, apps/ui/pages/reservations/[id].tsx, apps/ui/pages/terms/[id].tsx
=> Adds generic terms variants

apps/admin-ui/src/i18n/messages.ts
The one Elina noticed during ui review (filter) + missing pagination localisation.
=> fix (admin): missing translations

apps/ui/components/reservation/EditStep1.tsx, apps/ui/components/reservation/Step1.tsx
=> Fix link url in reservation funnel

apps/ui/public/locales/en/searchForm.json
=> fix erroneous english translation label

apps/ui/components/application/ApplicantInfoPreview.tsx, apps/ui/components/application/ApplicationEventList.tsx, apps/ui/components/application/Buttons.tsx, apps/ui/components/application/Form.tsx, apps/ui/components/application/OrganisationForm.tsx, apps/ui/components/application/ViewInner.tsx, apps/ui/components/common/Footer.tsx, apps/ui/pages/application/[...params].tsx, apps/ui/pages/application/[id]/page3.tsx, apps/ui/pages/application/[id]/preview.tsx, apps/ui/pages/application/[id]/view.tsx, apps/ui/pages/reservation-unit/[...params].tsx, packages/common/src/queries/application.ts
fix: missing application form fields after refactor
fix: saving application events after `priority` -> `preferredOrder` rename
refs: TILA-2948
=> fix: ui application view missing fields

apps/admin-ui/src/component/my-units/ShowTOS.tsx, apps/ui/components/application/ViewInner.tsx, apps/ui/components/reservation/EditStep1.tsx, apps/ui/mocks/handlers/reservationUnit.ts, apps/ui/pages/application/[id]/preview.tsx, apps/ui/pages/application/[id]/view.tsx, apps/ui/pages/reservation-unit/[...params].tsx, apps/ui/public/locales/sv/searchForm.json
Fixes equipments-label in Swedish and refactors all remaining `generic1` to `booking`.
=> Fix equipments+generic

apps/admin-ui/src/common/util.ts, apps/admin-ui/src/component/my-units/WeekNavigation.tsx
Finnish month format is 20.2. not 20.2
Refs: TILA-2480
=> fix: missing . from month format

apps/ui/components/common/Footer.tsx, apps/ui/public/locales/en/footer.json, apps/ui/public/locales/fi/footer.json, apps/ui/public/locales/sv/footer.json
=> Fix footer links to new terms pages

apps/ui/components/application/Page2.tsx, apps/ui/components/calendar/ReservationCalendarControls.tsx, apps/ui/components/reservation-unit/ReservationInfoContainer.tsx, apps/ui/components/reservation/EditStep0.tsx, apps/ui/modules/reservation.ts, apps/ui/pages/reservation-unit/[id].tsx, packages/common/src/calendar/util.ts
=> Show opening hours in application time selection

apps/ui/components/common/Navigation/NavigationUserMenu/NavigationUserMenu.tsx, apps/ui/components/common/Navigation/NavigationUserMenu/NavigationUserMenuUserCard.tsx, apps/ui/env.mjs, apps/ui/modules/queries/user.ts, apps/ui/public/locales/en/navigation.json, apps/ui/public/locales/fi/navigation.json, apps/ui/public/locales/sv/navigation.json, packages/common/types/gql-types.ts, tilavaraus.graphql
=> Adds profile link to menu for AdAuthenticated users

apps/ui/components/common/__tests__/ListWIthPagination.test.tsx, apps/ui/components/form/__tests__/MultiselectDropdown.test.tsx, apps/ui/components/reservation/__tests__/ReservationOrderStatus.test.tsx, apps/ui/components/reservation/__tests__/ReservationStatus.test.tsx, apps/ui/jest.config.mjs, apps/ui/jest.setup.mjs, apps/ui/modules/__tests__/reservation.test.ts, apps/ui/modules/__tests__/util.test.ts, apps/ui/modules/reservation.ts, apps/ui/package.json, apps/ui/tsconfig.json, packages/common/src/calendar/util.ts, pnpm-lock.yaml
- add Typescript checks to unit tests
- fix: 0 max days before days failing a test 
Ref: TILA-2745
=> Fix max days broke unit tests

apps/admin-ui/src/component/Unit/ReservationUnitList.tsx, apps/admin-ui/src/component/Unit/Unit.tsx, apps/admin-ui/src/i18n/messages.ts
- fix: incorrect text when unit has no reservation units
- refactor: unit page to use same layout components as other pages
Ref: TILA-2867
=> Fix no reservation unit text

apps/admin-ui/src/component/applications/time-selector/TimeSelector.tsx
=> fix: mobile layout breaking because of grid

apps/admin-ui/src/component/applications/queries.ts, packages/common/src/queries/application.ts
Fragment the queries because admin query reguires specific permissions.
Ref: TILA-2899
=> fix: broken application because of workingmemo

apps/ui/components/common/ListWithPagination.tsx, apps/ui/styles/global.scss, apps/ui/styles/util.ts, packages/common/src/components/IconButton.tsx
Overwrites the css-variables which hds-buttons use, to have correct theming on our primary and secondary buttons
=> Categorically fix button colors

apps/ui/components/reservation-unit/QuickReservation.tsx
- break the infinite loop
- restrict date selection to only valid days (can be bypassed with keyboard input)
=> fix: invalid date causing browser to freeze

apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx
fix: Incorrect value for a select.
fix: space change should update the surface and max persons.
Refs: TILA-2816
=> fix: unselectable interval and space change effect

apps/ui/middleware.ts, apps/ui/modules/const.ts, apps/ui/pages/reservation-unit/[id].tsx
fix: NextJs middleware breaks route locale in getServerSideProps
fix:  middleware auth redirects having incorrect url when behind a gateway
=> Fix UI middleware broke locale routing

apps/admin-ui/src/i18n/messages.ts, apps/admin-ui/src/spa/ReservationUnit/edit/form.ts, apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx
- allow switching draft <-> published without modification
- don't allow empty html tags without any text
- disallow negative minPerson / maxPerson numbers
Refs: TILA-2816
=> fix: edit reservation unit validation

apps/ui/components/reservation/ReservationEdit.tsx
Seconds / milliseconds cause the mutation fail an interval check on the backend so remove them before mutating.
=> fix: adjust time mutation failing randomly

apps/ui/components/calendar/ReservationCalendarControls.tsx, apps/ui/components/reservation-unit/QuickReservation.tsx, apps/ui/components/reservation/EditStep0.tsx, apps/ui/components/reservation/ReservationEdit.tsx, apps/ui/mocks/handlers/reservationUnit.ts, apps/ui/modules/__tests__/reservation.test.ts, apps/ui/modules/queries/reservationUnit.ts, apps/ui/modules/reservation.ts, apps/ui/modules/reservationUnit.ts, apps/ui/pages/reservation-unit/[id].tsx, packages/common/src/calendar/__tests__/calendar.test.ts, packages/common/src/calendar/util.ts, packages/common/src/common/__tests__/util.test.ts, packages/common/types/gql-types.ts, tilavaraus.graphql
Switches over to the new `reservableTimeSpans` implementation, from the old `openingTimes` one.
Attempts to refactor the code as much as possible, to simplify and clarify it.
Ref: TILA-2943
=> Reservable time spans front

apps/ui/components/calendar/ReservationCalendarControls.tsx, apps/ui/components/reservation-unit/QuickReservation.tsx, apps/ui/modules/__tests__/reservation.test.ts
The duration related fixes in reservationCalendarControls might fix some issues with the calendar, too.
=> Fixes the price not showing up in quick reservation

apps/admin-ui/src/component/BreadcrumbWrapper.tsx, apps/admin-ui/src/component/Unit/Unit.tsx, apps/admin-ui/src/component/applications/ApplicationDetails.tsx, apps/admin-ui/src/component/my-units/MyUnitView.tsx, apps/admin-ui/src/component/notifications/page.tsx, apps/admin-ui/src/component/recurring-reservations/ApplicationRound.tsx, apps/admin-ui/src/component/recurring-reservations/Criteria.tsx, apps/admin-ui/src/component/reservations/requested/RequestedReservation.tsx, apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx, packages/common/src/breadcrumb/Breadcrumb.tsx
fix: No full page refresh anymore when navigating.
refactor: remove search based alias (use array of structs instead).
=> fix: breadcrumb use react-router-dom link

apps/ui/components/calendar/ReservationCalendarControls.tsx, apps/ui/components/reservation-unit/QuickReservation.tsx, apps/ui/components/reservation/EditStep0.tsx, apps/ui/modules/reservation.ts, apps/ui/pages/reservation-unit/[id].tsx, packages/common/src/calendar/__tests__/calendar.test.ts, packages/common/src/calendar/util.ts
Should fix all the problems encountered after the API change.
=> Fixes reservation unit page calendar & quick reservation

apps/admin-ui/src/component/filters/SingleReservationUnitFilter.tsx, apps/admin-ui/src/component/filters/queries.ts, apps/admin-ui/src/component/my-units/MyUnitRecurringReservation/__test__/mocks.ts, apps/admin-ui/src/component/my-units/hooks/index.ts, apps/admin-ui/src/component/my-units/hooks/queries.ts, apps/admin-ui/src/component/my-units/queries.ts, apps/admin-ui/src/component/reservation-units/ReservationUnitsDataLoader.tsx, apps/admin-ui/src/component/reservation-units/queries.ts, apps/ui/components/reservation-unit/ReservationUnitModal.tsx, apps/ui/modules/queries/reservationUnit.ts, apps/ui/pages/reservation-unit/[id].tsx, apps/ui/pages/search/index.tsx, apps/ui/pages/search/single.tsx, packages/common/types/gql-types.ts, tilavaraus.graphql
Bump gql types to most recent core. 
- fix: ID -> Int change (string -> number)
=> chore: update gql types from core

apps/ui/components/form/DateRangePicker.tsx, apps/ui/components/single-search/FilterTagList.tsx, apps/ui/components/single-search/ReservationUnitCard.tsx, apps/ui/components/single-search/SearchForm.tsx, apps/ui/modules/queries/reservationUnit.ts, apps/ui/pages/search/single.tsx, apps/ui/public/locales/en/searchForm.json, apps/ui/public/locales/fi/searchForm.json, apps/ui/public/locales/sv/searchForm.json, packages/common/src/components/single-search/types.ts, tilavaraus.graphql
Adds time filters to single search, and status tags to the search result.
Refs: TILA-2853, TILA-2856
=> Add search time filters

apps/admin-ui/src/common/const.ts, apps/admin-ui/src/component/recurring-reservations/review/AllocatedEventDataLoader.tsx, apps/admin-ui/src/component/recurring-reservations/review/AllocatedEventsTable.tsx, apps/admin-ui/src/component/recurring-reservations/review/Review.tsx, apps/admin-ui/src/i18n/messages.ts
Adds the tab, but the table doesn't yet list the correct info (as it's a copy of ApplicationEventsDataLoader/Table with changes to the query).
=> Adds initial allocated events tab to recurring reservations review

apps/ui/modules/reservation.ts, apps/ui/pages/payment-return/index.tsx, apps/ui/pages/webstore-callback/index.tsx
=> Remove the user parameter from payment return url

apps/admin-ui/src/i18n/messages.ts, apps/admin-ui/src/schemas/schemaCommon.ts, apps/admin-ui/src/spa/ReservationUnit/edit/ActivationGroup.tsx, apps/admin-ui/src/spa/ReservationUnit/edit/PricingType.tsx, apps/admin-ui/src/spa/ReservationUnit/edit/SeasonalSection.tsx, apps/admin-ui/src/spa/ReservationUnit/edit/form.ts, apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx, packages/common/src/components/form/DateTimeInput.tsx
add: error summary to the top of the page
fix: validate the time intervals
fix: allow clearing time intervals from either checkbox
=> fix: validators and error summary

apps/ui/components/single-search/ReservationUnitCard.tsx, apps/ui/public/locales/en/application.json, apps/ui/public/locales/en/dateSelector.json, packages/common/src/components/form/TimeRangePicker.tsx
fix: status tag in wrong place on mobile layout
remove: address from search cards
fix: missing error icon in custom component
fix: incorrect en translation
=> Fix UI search cards

apps/ui/components/single-search/ReservationUnitCard.tsx, apps/ui/pages/search/single.tsx
CSS got overridden by HDS defaults.
=> Fix tag colours

apps/admin-ui/src/component/Resources/resource-editor/NewResourceModal.tsx, apps/admin-ui/src/component/Resources/resource-editor/ResourceEditor.tsx, apps/admin-ui/src/component/Spaces/space-editor/ParentSelector.tsx, apps/admin-ui/src/component/Spaces/space-editor/SpaceEditor.tsx, apps/admin-ui/src/component/Spaces/space-editor/new-space-modal/Page1.tsx
Fix: value sent to the select was incorrect
Remove: filtering based on child hierarchy
=> fix: can't add new resources

apps/ui/components/single-search/FilterTagList.tsx, apps/ui/pages/search/single.tsx
Remove use of toSorted and toReversed that don't work on older iOS versions.
=> Fix UI ios 15 crashing

apps/ui/components/LoginFragment.tsx, apps/ui/components/common/Navigation/Navigation.tsx, apps/ui/components/common/Navigation/NavigationUserMenu/NavigationUserMenu.tsx, apps/ui/components/reservation-unit/Head.tsx, apps/ui/components/reservation-unit/QuickReservation.tsx, apps/ui/hooks/user.tsx, apps/ui/pages/reservation-unit/[id].tsx, packages/common/src/calendar/Calendar.tsx, packages/common/src/calendar/Toolbar.tsx, packages/common/src/calendar/util.ts
Make the reservation calendar responsive even on low end systems.
fix: improve the slot generation performance by at least 10x
fix: login button should use previous data while loading
fix: SSR render components (hydration erros fixed)
fix: navigation links not having href
fix: remove ghost reservation in the calendar
fix: broken calendar link in quick reservation
=> Fix horrible calendar performance

apps/admin-ui/src/component/Unit/UnitsDataLoader.tsx, apps/admin-ui/src/component/reservation-units/ReservationUnitsDataLoader.tsx, apps/admin-ui/src/component/reservations/ReservationsDataLoader.tsx, apps/admin-ui/src/component/reservations/requested/ApproveDialog.tsx, apps/admin-ui/src/component/reservations/requested/RequestedReservation.tsx, apps/admin-ui/src/component/reservations/requested/util.ts, apps/ui/components/reservation-unit/ReservationUnitModal.tsx, apps/ui/components/reservation/ReservationInfoCard.tsx, apps/ui/mocks/handlers/reservation.ts, apps/ui/mocks/handlers/reservationUnit.ts, apps/ui/modules/__tests__/reservationUnit.test.ts, apps/ui/modules/reservationUnit.ts, apps/ui/pages/reservation-unit/[id].tsx, packages/common/codegen.yml, packages/common/types/gql-types.ts
Mutations accept number also so they at least used to work. A lot of the code did implicit string conversions, but some comparisons might have been broken.
Refs: TILA-2999
=> fix: gql decimal type is string not number

apps/admin-ui/src/component/Unit/UnitsTable.tsx, apps/admin-ui/src/component/reservation-units/ReservationUnitsTable.tsx, apps/admin-ui/src/component/reservations/ReservationsTable.tsx, apps/admin-ui/src/i18n/messages.ts, apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/AllocatedEventsTable.tsx, apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/ApplicationEventsTable.tsx, apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/ApplicationsTable.tsx
=> fix: empty filter result message

apps/ui/components/calendar/ReservationCalendarControls.tsx, apps/ui/components/reservation-unit/Head.tsx, apps/ui/components/reservation-unit/QuickReservation.tsx, apps/ui/modules/util.ts, apps/ui/pages/reservation-unit/[id].tsx
Fixes the redirect, and implements it in QuickReservation.
Also adds check for the reservation quota before creating a reservation (otherwise the user could bypass the quota with a post login reservation).
=> Fix login & reserve redirect

apps/ui/components/common/BreadcrumbWrapper.tsx, apps/ui/components/reservation-unit/Address.tsx, apps/ui/components/reservation-unit/Head.tsx, apps/ui/components/reservation-unit/Images.tsx, apps/ui/components/reservation-unit/RelatedUnits.tsx, apps/ui/components/reservation-unit/ReservationUnitCard.tsx, apps/ui/components/reservation-unit/ReservationUnitModal.tsx, apps/ui/components/reservation/EditStep0.tsx, apps/ui/components/reservation/ReservationCard.tsx, apps/ui/components/reservation/ReservationEdit.tsx, apps/ui/components/reservation/ReservationInfoCard.tsx, apps/ui/components/search/ReservationUnitCard.tsx, apps/ui/components/single-search/ReservationUnitCard.tsx, apps/ui/modules/util.ts, apps/ui/pages/reservation-unit/[id].tsx, apps/ui/pages/reservations/[id]/index.tsx, packages/common/src/breadcrumb/Breadcrumb.tsx, packages/common/src/components/IconButton.tsx
- fix: double testids on edit reservation page 
- fix: spacing issues when reservation unit had an image
- add: fallback to grey pixel if reservation unit is missing an image
- fix: missing images when using locally
- fix: reservation page missing a breadcrumb on mobile
- add: disabled link style to IconButton
- fix: IconButton with empty links
Refs: TILA-3087
=> Fix reservation page spacing issues

apps/ui/modules/queries/fragments.ts, apps/ui/modules/queries/reservation.ts, apps/ui/modules/queries/reservationUnit.ts
Fragment queries where easily possible to avoid code duplication, and similar errors in the future.
=> fix: missing fields in reservation query

apps/ui/modules/reservationUnit.ts
Removes unwanted early return when priceUnit is FIXED
=> fix: show lower price with fixed pricing

packages/common/package.json, pnpm-lock.yaml
Apollo installed both as regular and dev dependency, it's only a peer dependency for common.
=> chore: remove extra apollo dep

apps/admin-ui/src/component/applications/ApplicationDetails.tsx
- Remove extra link in breadcrumb.
- Check application (details) page the last element in breadcrumb should not be a link.
- TILA-####
=> fix: extra link in breadcrumb on application page

.github/dependabot.yml
- Add: dependabot config
-
- TILA-####
=> add: dependabot

apps/admin-ui/src/component/my-units/BufferToggles.tsx, apps/admin-ui/src/component/my-units/ReservationTypeForm.tsx, apps/admin-ui/src/component/my-units/create-reservation/CreateReservationModal.tsx, apps/admin-ui/src/component/reservations/EditTimeModal.tsx, apps/admin-ui/src/helpers/date.ts, apps/admin-ui/src/i18n/locales/fi/reservationForm.json, apps/admin-ui/src/schemas/reservation.ts, apps/admin-ui/src/spa/ReservationUnit/edit/form.ts
- Fix: empty buffers rendering 0 instead of being hidden in the form.
- Fix: validate the form that reservation can't start before now.
- In admin ui try making a reservation using the single reservation modal to a past date or time. 
- TILA-3017
=> Fix admin single reservation validators

apps/admin-ui/src/component/reservations/ReservationsTable.tsx, apps/admin-ui/src/component/reservations/fragments.ts, apps/admin-ui/src/component/reservations/requested/DenyDialog.tsx, apps/admin-ui/src/component/reservations/requested/RequestedReservation.tsx, apps/admin-ui/src/component/reservations/requested/ReservationTitleSection.tsx, apps/admin-ui/src/component/reservations/requested/hooks/queries.ts, apps/ui/components/reservations/UnpaidReservationNotification.tsx, apps/ui/modules/__tests__/reservation.test.ts, apps/ui/modules/queries/reservation.ts, apps/ui/modules/reservation.ts, apps/ui/pages/reservation/confirmation/[id].tsx, apps/ui/pages/reservations/[id]/index.tsx, packages/common/types/gql-types.ts, tilavaraus.graphql
Newest core added the payment order link to reservation instead of separate fields.
=> breaking: backend payment order api change

apps/ui/components/common/StartApplicationBar.tsx, apps/ui/middleware.ts, apps/ui/pages/intro.tsx, packages/common/src/urlBuilder.ts
- Fix: login redirect when making a new seasonal reservation application.
- Fix: use SSR to query the possible reservation-units for seasonal reservation.
- Fix: use a Link instead of router.push for next button.
- Create a new application for seasonal reservation as a non logged in user.
- TILA-####
=> Fix protected route middleware

apps/admin-ui/src/common/queries.ts, apps/admin-ui/src/component/reservations/ReservationsDataLoader.tsx, apps/admin-ui/src/component/reservations/queries.ts, apps/admin-ui/src/hooks/useHandling.ts, apps/ui/components/reservation/ReservationEdit.tsx, apps/ui/modules/queries/reservation.ts, apps/ui/pages/reservation-unit/[id].tsx, apps/ui/pages/reservations/index.tsx
- Fix: PR https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/993
- Typescript checks aren't enough for GQL queries, they aren't linted or typechecked.
- Check any reservation pages (they should work like before, and there should be no failed graphql network requests).
- TILA-3096
=> fix: breaking gql reservation api changes

apps/ui/components/reservation/Step0.tsx, apps/ui/pages/reservation-unit/[...params].tsx
- Fix: forms that didn't include home city would not allow making reservations.
- Test all the different forms used for reservations particularly the ones without homeCity or reserveeType.
- TILA-####
=> fix: can't make reservation if there is no city

apps/admin-ui/src/i18n/messages.ts, packages/common/src/calendar/util.ts, packages/common/types/gql-types.ts, tilavaraus.graphql
- Add new reservation interval choices for hours 2 - 7
- See Jira ticket
- [TILA-3177](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3177)
---
[TILA-3177]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add translations for new reservation interval values

.github/dependabot.yml
- Remove massive npm grouping, it will never work.
- Pin versions that can't be updated automatically.
- Add some fine tuned groups.
- Pipeline / automation update. No direct changes to the app.
- TILA-####
=> improve dependabot

.github/dependabot.yml
- Use a separate PR group for dependencies that require manual updated.
- Add: `date-fns` and `@types` to manual update group.
- Add: major `react` update to manual group.
- automation / pipeline change
- TILA-####
=> chore: add manual update group to dependabot

packages/common/email/i18n/en.json, packages/common/email/i18n/fi.json, packages/common/email/i18n/sv.json, packages/common/email/templates/applicationHandled.template.mjml, packages/common/email/templates/applicationInHandling.template.mjml, packages/common/email/templates/applicationReceived.template.mjml, packages/common/email/text-templates/applicationHandled.template.txt, packages/common/email/text-templates/applicationInHandling.template.txt, packages/common/email/text-templates/applicationReceived.template.txt
- Add new Application-type Email Templates
- If testing manually, needs to be tested together with https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1137
- [TILA-3219](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3219)
[TILA-3219]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add new Application-type Email Templates

apps/ui/components/applications/ApplicationCard.tsx, apps/ui/modules/util.ts, apps/ui/public/locales/en/applicationCard.json, apps/ui/public/locales/sv/applicationCard.json, packages/common/styles/buttonCss.ts
- fix: bug that occurred in testing when changing round end time.
- base the mutability of application to the status the backend provides. 
- more stable code when we don't do duplicated checks in the frontend.
- application list should allow edit / delete any applications as long as the round is not closed (even if switching round end time).
- TILA-####
=> fix: use application state to disable edit

apps/ui/components/common/PageWrapper.tsx, apps/ui/components/reservation/Step0.tsx, apps/ui/components/reservations/UnpaidReservationNotification.tsx, apps/ui/hooks/reservation.tsx, apps/ui/hooks/useConfirmNavigation.ts, apps/ui/modules/util.ts, apps/ui/pages/reservation-unit/[...params].tsx, apps/ui/pages/reservations/[id]/index.tsx, apps/ui/public/locales/en/notification.json, apps/ui/public/locales/en/reservations.json, apps/ui/public/locales/fi/notification.json, apps/ui/public/locales/fi/reservations.json, apps/ui/public/locales/sv/notification.json, apps/ui/public/locales/sv/reservations.json
- Add: confirmation dialog when navigating away from the reservation funnel.
- Add: Notification of a pending reservation.
- Manual testing based on the spec in the tickets.
- [TILA-3227](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3227)
- [TILA-3226](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3226)
[TILA-3227]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TILA-3226]: …
=> Add confirmation when exiting reservation process

apps/admin-ui/src/component/reservations/requested/ApproveDialog.tsx
- Fix: Approve a reservation with a fee, the fee set to zero checkbox not toggling checked state correctly.
- Reservations that require payment and approval should have to fee / price setting correct when set to free.
- TILA-####
=> fix: approve with free price toggle

apps/admin-ui/src/component/reservations/requested/ReservationTitleSection.tsx
- Add: testid to status tag as request
-
- TILA-####
=> add: testids to admin reservation view

apps/ui/components/reservation/EditStep0.tsx, apps/ui/components/reservation/ReservationEdit.tsx, apps/ui/modules/reservation.ts, apps/ui/modules/reservationUnit.ts, apps/ui/pages/reservation-unit/[id].tsx, packages/common/src/calendar/Calendar.tsx
- Fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1025
- Time format change from `ISO` -> `ui` broke the pages in some situations.
- Edit and new reservation pages refactoring (same as the original PR).
- TILA-####
=> fix: reservation edit time formats

apps/ui/components/application/ApplicationEvent.tsx, apps/ui/components/application/BillingAddress.tsx, apps/ui/components/application/CompanyForm.tsx, apps/ui/components/application/EmailInput.tsx, apps/ui/components/application/Form.tsx, apps/ui/components/application/IndividualForm.tsx, apps/ui/components/application/OrganisationForm.tsx, apps/ui/pages/application/[id]/page3.tsx, apps/ui/public/locales/en/application.json, apps/ui/public/locales/fi/application.json, apps/ui/public/locales/sv/application.json
- Fix: application form validation too large character limits compared to the current backend limits so the mutation failed without a proper error message. 
- Creating a new application should not fail with a backend error, instead all field length errors should be shown in the form.
- [TILA-3258](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3258)
[TILA-3258]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: application incorrect validation limits

apps/admin-ui/src/schemas/reservation.ts
- Desired feature and backend supports new admin reservations for the same day regardles of time.
-
- [TILA-3252](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3252)
[TILA-3252]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: allow creating reservations today in the past

apps/ui/components/reservation-unit/QuickReservation.tsx
- Fix: quick reservation price and button having zero spacing.
- style change: quick reservation component should look normal.
- TILA-####
=> fix: quick reservation spacing

apps/ui/components/applications/ApplicationCard.tsx, apps/ui/modules/util.ts, apps/ui/pages/applications.tsx, apps/ui/public/locales/en/applicationCard.json, apps/ui/public/locales/en/applications.json, apps/ui/public/locales/fi/applicationCard.json, apps/ui/public/locales/fi/applications.json, apps/ui/public/locales/sv/applicationCard.json, apps/ui/public/locales/sv/applications.json, packages/common/types/common.ts
- Add: separate status for handled versus just sent applications per round status.
- If the application round has ended the application should automatically be moved to top section that is separate from sent applications (they can't be edited).
- [TILA-3233](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3233)
[TILA-3233]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add: application processed status

apps/ui/middleware.ts, apps/ui/modules/apolloClient.ts
- Fix: ui not working without being logged in after backend added csrf token checks to graphql endpoint.
- Graphql is only POST requests and Django wants the csrf token to be set before making a POST request. So if the cookie is not set we need to make separate dummy GET request on both SSR and Browser to fix that.
- Requires: https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1161
- Replaces: https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1129
- Deployment should always fail because of health checks if the SSR version doesn't work.
- Browser version can be checked from search page (if it …
=> fix: get csrf token before making graphql requests

apps/admin-ui/src/pages/healthcheck.tsx, apps/ui/middleware.ts, apps/ui/pages/healthcheck.tsx
- Add separate health check pages for both apps that do no GraphQL requests.
- Automation / deployment change: check Kubernetes and Azure devops logs, there should be no errors.
- TILA-####
=> add: devops / kubernetes health check pages

apps/ui/components/calendar/ReservationCalendarControls.tsx, apps/ui/components/common/ControlledSelect.tsx, apps/ui/components/reservation-unit/QuickReservation.tsx, apps/ui/components/reservation-unit/schema.ts, apps/ui/modules/queries/reservationUnit.tsx, apps/ui/pages/reservation-unit/[id].tsx
- Fix: initial duration incorrect on some options.
- Fix: keyboard input date crashing the reservation page.
- Refactor: remove undefined values from reservation form.
- Fix: denied (removed) reservations blocking new and moving reservations.
- Fix: remove custom placeholder from CalendarControls.
- TILA-####
=> Fix reservation page bugs

apps/ui/components/search/SeasonalSearchForm.tsx, apps/ui/components/search/SingleSearchForm.tsx, apps/ui/modules/search.ts
- Fix: Mistyped filter name on search pages (form is typed, but the query params are not).
- Manual testing: search filters on both pages.
- TILA-####
=> fix: search reservation type filter not working

apps/ui/components/reservation-unit/utils.ts
- Fix: quick reservation next available time didn't check against existing reservations so it returned incorrect days. 
- Manual testing: quick reservation.
- TILA-####
=> fix: next available time didn't find anything

apps/admin-ui/src/component/reservations/EditTimeModal.tsx, apps/admin-ui/src/component/reservations/requested/util.ts, apps/admin-ui/src/i18n/messages.ts, apps/admin-ui/src/schemas/utils.ts, apps/admin-ui/src/spa/ReservationUnit/edit/form.ts, apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx, apps/ui/components/reservation/EditStep0.tsx, apps/ui/pages/reservation-unit/[id].tsx, packages/common/src/calendar/util.ts, packages/common/types/common.ts
- Fix: (admin) minutes were not shown when moving a reservation only hours.
- Fix: (ui) reservation buffers not shown while making a reservation.
- Fix: (admin) reservation unit edit missing start duration / interval mutation validations. 
- Manual testing: problems reported in Slack.
- [TILA-3232](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3232)
[TILA-3232]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix buffers not visible when reserving

apps/admin-ui/src/component/reservations/requested/RecurringReservationsView.tsx
- Fix: https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1165 `<` and `>` got mixed.
-
- TILA-####
=> fix: allow decline future recurring reservation

apps/ui/modules/queries/reservationUnit.tsx, apps/ui/pages/reservation-unit/[id].tsx, packages/common/types/gql-types.ts, tilavaraus.graphql
Reverts City-of-Helsinki/tilavarauspalvelu-ui#1164
Backend queries timeout in production.
=> Revert "fix: use active reservations in reservation quota check"

apps/ui/components/reservation/Step1.tsx
- Refactor removed data-testids on the second page of making a new reservation.
-
- TILA-####
=> add: missing reservation confirm test ids

apps/admin-ui/src/component/reservations/requested/ApproveDialog.tsx, apps/admin-ui/src/component/reservations/requested/DenyDialog.tsx, apps/admin-ui/src/component/reservations/requested/ReturnToRequiresHandlingDialog.tsx, apps/ui/components/reservation/ReservationCancellation.tsx, packages/common/types/gql-types.ts, tilavaraus.graphql
- Update GQL types to match core https://github.com/City-of-Helsinki/tilavarauspalvelu-core/releases/tag/v0.44.0
- Manual testing (fixes compatibility between the two).
- TILA-####
=> fix: core 0.44.0 gql api update

apps/ui/components/common/Navigation/NavigationUserMenu/NavigationUserMenu.tsx
- Add: testid to customer login button.
-
- TILA-####
=> add: testid to login button

.github/dependabot.yml, .github/workflows/pipeline.yml, apps/admin-ui/package.json, package.json, pnpm-lock.yaml
- Add: dependabot rule not to upgrade eslint.
- Remove one unused dependency.
- Upgrade pnpm
- Remove conflicting pnpm version from CI config.
- Automated tests / lint.
- TILA-####
=> Chore: dep bump

apps/ui/gql/gql-types.ts, apps/ui/modules/queries/reservationUnit.tsx
- Fix: cancelled (and other invalid) reservations showing up in reservation calendar and blocking a new reservation.
- Manual testing: neither edit nor new reservation should be blocked by a `Cancelled` reservation.
- [TILA-3327](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3327)
[TILA-3327]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: cancelled reservations blocking reservation

apps/ui/components/reservation/ReservationCancellation.tsx, apps/ui/components/reservation/ReservationEdit.tsx, apps/ui/components/reservations/styles.tsx, apps/ui/pages/reservations/[id]/cancel.tsx
- reuse styling from edit page
- remove double testids
- fix: check if the reservation can be cancelled and don't show the page if not.
- Manual testing: cancel page should not be accessible if the reservation is not cancellable.
- Manual testing: styling for cancel pages (responsiveness).
- [TILA-3418](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3418)
[TILA-3418]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: cancel reservation page

apps/admin-ui/gql/gql-types.ts, apps/admin-ui/src/component/Unit/UnitsDataLoader.tsx, apps/ui/gql/gql-types.ts, packages/common/gql/gql-types.ts, tilavaraus.graphql
- Update API to: https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1239
- Bugfix to https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1194
- Automated testing: type lint against the new API. 
- Manual testing: alphabetic ordering of unit groups should now work.
- TILA-####
=> fix: api change to unit group ordering

apps/ui/modules/reservation.ts
- Fix: button missing 'cause failing a check with too aggressive null checks (the function works with partial data for multiple cases).
- Manual testing: reservation that is editable should have the link / btn to edit page.
- TILA-####
=> fix: reservation edit button missing

apps/admin-ui/src/component/RichTextInput.tsx, apps/admin-ui/src/component/my-units/UnitCalendar.tsx, apps/admin-ui/src/component/my-units/create-reservation/CreateReservationModal.tsx, apps/admin-ui/src/component/notifications/page.tsx, apps/admin-ui/src/component/reservations/requested/RequestedReservation.tsx, apps/ui/pages/reservations/index.tsx, packages/common/src/components/BannerNotificationsList.tsx, packages/common/src/components/NotificationWrapper.tsx
- Add data testids as requested.
-
- TILA-####
=> add: data testids

apps/admin-ui/src/component/Table.tsx, apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/AllocatedEventsTable.tsx, apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/ApplicationEventsTable.tsx, apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/ApplicationsTable.tsx
- Fix: development versio throwing errors because of a key value added to handle ghost elements in table.
- Fixes a bug in https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1237 only affecting development builds.
-
- TILA-####
=> fix: debug error from circular component key

apps/admin-ui/gql/gql-types.ts, apps/admin-ui/src/helpers/index.ts, apps/admin-ui/src/spa/applications/[id]/index.tsx, apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/AllocationCard.tsx, apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/RejectedOccurrencesDataLoader.tsx, apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/utils.ts, apps/ui/components/application/AddressPreview.tsx, apps/ui/components/application/ApplicantInfoPreview.tsx, apps/ui/components/application/ApplicationPage.tsx, apps/ui/components/application/Form.tsx, apps/ui/components/applications/ApplicationCard.tsx, apps/ui/gql/gql-types.ts, apps/ui/pages/application/[id]/page3.tsx, packages/common/gql/gql-types.ts, packages/common/src/queries/application.tsx, tilavaraus.graphql
- Fix: organisation name missing in the query.
- Refactor: use Fi translations over base version so backend optimiser works.
- Fix: few old enums left in the typedefs even though backend removed them (and translations were removed). 
- https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1257
- Manual testing: rejected table applicant names (also check application -> applicant name / address they should not have changed).
- TILA-####
=> Fix missing applicant name in rejected table

apps/ui/components/calendar/ReservationCalendarControls.tsx, apps/ui/pages/reservations/[id]/index.tsx
- Fix: Use new time format utility function in the last two places (reservation page and CalendarControls).
- Fix: missing reservation time on reservation page title.
- Manual testing: no old time formats (ex. hyphens) should be found in customer ui. 
- [TILA-3444](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3444)
[TILA-3444]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove time format copy pasta

Dockerfile
- Change to use ECR instead of docker.io as registry because we are hitting pull limits on Azure.
- Build change: if it gets deployed it works.
- TILA-####
=> change docker registry to AWS ECR

apps/admin-ui/src/component/reservations/requested/RequestedReservation.tsx
- Add: test ids to all key value pairs on reservation page (admin-ui).
- Refactor: summary and other key values to use same code (different styling).
- Fix: cleaner word wrapping on mobile (without use of max-width).
- Automated tests (e2e): old and new data-testids should be correct on admin reservation page.
- TILA-####
=> add: testids to admin reservation

apps/ui/gql/gql-types.ts, apps/ui/modules/queries/reservationUnit.tsx, apps/ui/pages/reservation-unit/[id].tsx
- Requires backend changes: query timeout's only in production.
- https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1164
- original reverted waiting for backend changes
- Manual testing: check original PR.
- TILA-3236
=> Reservation quota amount

apps/ui/gql/gql-types.ts, apps/ui/modules/queries/params.tsx, apps/ui/pages/search/index.tsx, apps/ui/pages/search/single.tsx
- Requires backend changes: query timeout's only in production.
- https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1166
- original reverted waiting for backend changes
- Manual testing: see original PR.
- TILA-3247
- TILA-3248
=> fix: only relevant units are shown in search filter

apps/admin-ui/src/component/reservations/ReservationsDataLoader.tsx
- Fix: default filters removed those that requested subvented in reservation list (admin-ui).
- Manual testing: subvented should be shown by default (no way to exclude them with ui filters).
- TILA-####
=> fix: default not to filter by subvention request

apps/admin-ui/src/component/reservations/requested/ApproveDialog.tsx
- Fix: calculating and sending incorrect net price when approving a reservation.
- Manual testing: when approving a reservation with a price change the final reservation (ex. in Django) should have the correct net price. 
- [TILA-3462](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3462)
[TILA-3462]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: incorrect net price calculation

apps/admin-ui/src/component/ReservationsList.tsx
- fix: unit permissions checked against reservation unit and not unit.
- fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1318
- Manual testing: same as the original card.
- [TILA-3348](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3348) (bugfix)
[TILA-3348]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: unit permissions when adding to recurring

apps/admin-ui/src/component/reservations/requested/Calendar.tsx
- Fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1318
- edit time button translation key changed
-
- TILA-####
=> fix: incorrect button translation

apps/admin-ui/src/common/urls.ts, apps/admin-ui/src/component/Navigation.tsx
- Fix: incorrect url from the HDS / navigation change (and use constants for them). `admin-ui`
- Fix: use react-router navigation instead of `<a>` links so navigation is smoother.
- Manual testing: same as the other HDS / navigation changes.
- TILA-####
=> Fix admin navigation urls

apps/ui/components/common/Navigation.tsx
- fixes language selection in the header navigation
- Change the language on client pages
- TILA-####
=> fix: language selection in header navigation

apps/admin-ui/src/component/Navigation.tsx, apps/ui/components/common/Navigation.tsx
- Makes the navigation header's active page text bold
- Check that the active page text is bold
- TILA-####
=> fix: make the active page text bold

apps/ui/components/common/Navigation.tsx
- Replace language selector with responsive version.
-
- TILA-####
=> fix: language selector responsiveness

apps/admin-ui/gql/gql-types.ts, apps/admin-ui/src/common/util.ts, apps/admin-ui/src/component/ReservationsList.tsx, apps/admin-ui/src/component/reservations/EditPage.test.tsx, apps/admin-ui/src/component/reservations/EditTimeModal.tsx, apps/admin-ui/src/component/reservations/hooks/__test__/mocks.ts, apps/admin-ui/src/component/reservations/hooks/hooks.test.tsx, apps/admin-ui/src/component/reservations/hooks/index.ts, apps/admin-ui/src/component/reservations/requested/RecurringReservationsView.tsx, apps/admin-ui/src/component/reservations/requested/hooks/index.ts, apps/admin-ui/src/i18n/messages.ts, apps/admin-ui/src/spa/my-units/[id]/CreateReservationModal.tsx, apps/admin-ui/src/spa/my-units/recurring/RecurringReservationDone.tsx, apps/admin-ui/src/spa/my-units/recurring/RecurringReservationForm.test.tsx, apps/admin-ui/src/spa/my-units/recurring/RecurringReservationForm.tsx, apps/admin-ui/src/spa/my-units/recurring/__test__/mocks.ts, apps/admin-ui/src/spa/my-units/recurring/hooks/useCreateRecurringReservation.tsx, apps/admin-ui/src/spa/my-units/recurring/hooks/useFilteredReservationList.tsx, apps/admin-ui/src/spa/my-units/recurring/hooks/useMultipleReservation.tsx, apps/admin-ui/src/spa/my-units/recurring/utils.ts, apps/admin-ui/src/spa/my-units/router.tsx, packages/common/src/apolloUtils.ts, packages/common/src/helpers.ts, packages/common/src/reservation-form/MetaFields.tsx
- refactor: use a new series mutation to create recurring reservations
- fix: persistency of the page after creating a new recurring reservation (refresh / copy url).
- fix: show the number of reservations in a series without the ones that are removed.
- Manual testing: creating a new recurring reservation should work as before (except it's faster and the two linked bugs are fixed). 
- [TILA-3288](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3288)
- [TILA-3352](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3352)
- …
=> Refactor creation of reservation series

apps/ui/components/reservation-unit/utils.test.ts, apps/ui/components/reservation-unit/utils.ts, apps/ui/pages/reservation-unit/[id].tsx, packages/common/src/calendar/Toolbar.tsx
- Fix: a week without reservation time breaking the calendar navigation.
- Fix: don't modify date when calculating reservability.
- Refactor: remove unnecessary optionals.
- Manual testing: see Jira tickets for test cases.
- [TILA-3499](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3499)
- [TILA-3510](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3510)
[TILA-3499]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> Fix non reservable weeks breaking calendar

apps/admin-ui/src/component/reservations/requested/Calendar.tsx, apps/admin-ui/src/component/reservations/requested/RecurringReservationsView.tsx, apps/admin-ui/src/i18n/messages.ts, apps/admin-ui/src/spa/ReservationUnit/edit/form.ts, apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/index.tsx, apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/Review.tsx
- Fix: incorrect character limit for reservation unit editor causing backend form validation error.
- Fix: application-round pages allowing `units` the user has no access through from the URL.
- Fix: reservation page having edit time buttons (both single and recurring) even when the user has no access.
- TILA-####
=> Fix missing permission checks

apps/admin-ui/src/component/reservations/requested/RecurringReservationsView.tsx
- Fix: don't show individual deny buttons for recurring reservation if the user doesn't have permissions.
- [TILA-3139](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3139)
[TILA-3139]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove recurring deny button if no permission

packages/common/src/common/toast.tsx
- Fix: toasts not auto closing without explicit duration (autoClose not defined for default value).
-
- TILA-####
=> fix: auto close toasts

apps/admin-ui/gql/gql-types.ts, apps/admin-ui/src/component/reservations/requested/ApproveDialog.tsx, apps/ui/gql/gql-types.ts, packages/common/gql/gql-types.ts, tilavaraus.graphql
- Fix: core api change in https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1304
- Manual testing: Approve price should work as before.
- [TILA-3472](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3472)
[TILA-3472]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: core api change

apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/utils.ts
- Adds Rejected to the list of ApplicationSectionStatusChoice enums
- Selecting `Rejected` should now work as a filter
- TILA-3442
=> Adds Rejected to the list of ApplicationSectionStatusChoice enums

apps/admin-ui/src/component/reservations/requested/util.ts, apps/admin-ui/src/i18n/index.ts
- Fix: don't round tax percentage (include one decimal).
- Fix: add missing translations.
- Manual testing: Approval dialog tax display.
- TILA-####
=> Fix dont round tax percentage

apps/admin-ui/gql/gql-types.ts, apps/admin-ui/src/component/reservation-units/Filters.tsx, apps/admin-ui/src/component/reservation-units/ReservationUnitsDataLoader.tsx, apps/admin-ui/src/component/reservation-units/ReservationUnitsTable.tsx, apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx, apps/admin-ui/src/spa/ReservationUnit/edit/tags.tsx
- Fix: missing API type changes for https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1278
- Automated: lint / build.
- TILA-####
=> fix: type errors from api change

apps/admin-ui/gql/gql-types.ts
- Fix: rerun codegen to avoid polluting other diffs.
- Automated: lint / typecheck.
- TILA-####
=> fix: run codegen after file moves

apps/ui/pages/reservations/[id]/index.tsx
- Fix: broken test-id after prop rename.
- Automation.
- TILA-####
=> fix: test id prop rename on reservation page

.gitignore
- Adds vs code local config files/dir to .gitignore
-
- TILA-####
=> add: vscode local launcher stuff to .gitignore

apps/admin-ui/src/spa/my-units/recurring/hooks/useCreateRecurringReservation.tsx
- Fix: can't save new series with an age group `admin-ui`
- Manual testing
- [TILA-3597](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3597)
[TILA-3597]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: can't create series with age group

apps/admin-ui/src/component/QueryParamFilters/DayNavigation.tsx
- fix: day label mobile position overlapping with the day selector
- Manual testing: my units calendar responsivity of the date picker. `admin-ui`
- TILA-####
=> fix: day selector label mobile position

apps/admin-ui/src/spa/ReservationUnit/edit/form.ts
- Fix: don't show past pricings when editing reservation unit `admin-ui`
- Fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1458
- Manual testing: reported test reservation units should only show one active and one future price.
- TILA-####
=> fix: dont show past pricings

apps/admin-ui/src/spa/my-units/[id]/CreateReservationModal.tsx
- Add: requested `data-testid` to collision warning `admin-ui`
-
- TILA-####
=> add: data-test-id to new reservation collision warning

apps/admin-ui/gql/gql-types.ts, apps/admin-ui/src/spa/my-units/[id]/UnitCalendar.tsx, apps/admin-ui/src/spa/my-units/[id]/UnitReservations.tsx, apps/admin-ui/src/spa/my-units/[id]/hooks/index.ts, apps/admin-ui/src/spa/my-units/[id]/hooks/queries.tsx
- Refactor: remove double fetching reservations for calendar.
- Fix: days on which daylight savings occurs having +1 hour in the individual reservations.
- Manual testing: check the reservation times for day 27.10.
- Manual testing: check that space hierarchy blocks `admin-ui` reservation calendar.
- [TILA-3655](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3655)
[TILA-3655]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix incorrect calendar time daylight savings

apps/admin-ui/gql/gql-types.ts, apps/ui/components/SortingComponent.tsx, apps/ui/components/common/ListWithPagination.tsx, apps/ui/gql/gql-types.ts, apps/ui/modules/__tests__/reservation.test.ts, apps/ui/modules/__tests__/reservationUnit.test.ts, apps/ui/package.json, packages/common/gql/gql-types.ts, pnpm-lock.yaml, tilavaraus.graphql
- Chore: update gql types to match core `v0.76.0`
- Fix: hydration error on `search/single` page
- Chore: remove `react-i18next` from customer ui to avoid accidental imports.
- Automation: e2e / lint.
- TILA-####
=> Update GQL types

apps/ui/components/application/ApplicationEvent.tsx, packages/common/src/components/ConfirmationDialog.tsx
- Fix: missing translation in application confirm delete modal.
- Manual testing: edit application should have correct translations for deleting an application section. 
- TILA-####
=> fix: missing translations in confirmation modal

apps/ui/components/Accordion.tsx, apps/ui/components/AccordionWithIcons.tsx, apps/ui/components/application/ApplicationEvent.tsx, apps/ui/components/application/ApprovedReservations.tsx, apps/ui/components/application/Page2.tsx, apps/ui/components/application/styled.tsx, apps/ui/components/reservation/Step0.tsx, apps/ui/gql/gql-types.ts, apps/ui/modules/queries/application.tsx, apps/ui/modules/urls.ts, apps/ui/modules/util.ts, apps/ui/next-i18next.config.js, apps/ui/pages/applications/[id]/view/[section]/index.tsx, apps/ui/pages/applications/[id]/view/index.tsx, apps/ui/pages/reservation-unit/[id].tsx, apps/ui/pages/reservations/[id]/index.tsx, apps/ui/public/locales/en/application.json, apps/ui/public/locales/fi/application.json, apps/ui/public/locales/sv/application.json, codegen.ts, packages/common/src/common/util.ts, packages/common/src/components/IconButton.tsx, packages/common/src/components/Tag.tsx, packages/common/src/components/index.ts, packages/common/src/helpers.test.ts, packages/common/src/helpers.ts, packages/common/styles/buttonCss.ts
- Add: seasonal reservation page to list next reservations.
- Add: seasonal reservation page to list all reservations.
- Manual testing: create a new seasonal reservation (allocate it, and change it to `SENT` state), the new customer page should list the reservations correctly. 
- [TILA-3585](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3585)
- [TILA-3595](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3595)
- [TILA-3596](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3596)
[TILA-3585]: …
=> Add seasonal approved reservations page

apps/ui/components/application/ApprovedReservations.tsx, apps/ui/public/locales/en/application.json, apps/ui/public/locales/fi/application.json, apps/ui/public/locales/sv/application.json, packages/common/src/components/IconButton.tsx, packages/common/src/components/StatusLabel.tsx, packages/common/styles/buttonCss.ts
- Add  mobile version of application reservations `customer ui`
- Manual testing: similar to the approved reservations but on mobile (and responsiveness). 
- [TILA-3603](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3603)
[TILA-3603]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add: application mobile layout for a table

apps/ui/components/reservation/ReservationInfoCard.tsx
- Fix: reservation cards having double reservation ids.
- Automated: e2e
- TILA-####
=> fix: double reservation id on cards

apps/admin-ui/src/spa/reservations/[id]/ReservationTitleSection.tsx
- fix: incorrect translation in status label
-
- TILA-####
=> fix: incorrect tr key in status tag

apps/admin-ui/src/spa/application-rounds/[id]/review/ApplicationEventsTable.tsx, apps/admin-ui/src/spa/reservations/[id]/ReservationTitleSection.tsx
- fix: incorrect applicationSection status translation.
- fix: missing test id in status tag
-
- TILA-####
=> Fix status tag trs

apps/ui/middleware.ts
- Fix: optimisation don't make backend requests on asset load (only on page load).
- Fix: don't save incorrect language because of asset load on `/confirmation` page.
- Optimisation: don't make multiple user requests to the backend.
- Manual testing: bug fix for language saving.
- Manual testing: protected routes -> should redirect to login.
- TILA-####
=> fix: middleware running on asset requests

apps/ui/components/search/SeasonalSearchForm.tsx, apps/ui/components/search/SingleSearchForm.tsx, apps/ui/hooks/useSearchValues.tsx, apps/ui/modules/search.ts, apps/ui/modules/urls.ts
- Fix: front page text search param not applied correctly on route change.
- Fix: search values can't be removed using the form (clear buttons or removing text) without adding / changing another value.
- Manual testing: front page search should include the text param.
- Manual testing: search forms (both single and seasonal) should work normally (+ clearing values works).
- TILA-####
=> fix: front page search not working

pnpm-lock.yaml
- fix: lock file breaking because of dep update
- automated: build system broken
- TILA-####
=> fix: broken lock file

apps/ui/components/AccordionWithIcons.tsx, apps/ui/components/application/ApprovedReservations.tsx, apps/ui/public/locales/en/application.json, apps/ui/public/locales/fi/application.json, apps/ui/public/locales/sv/application.json, apps/ui/public/locales/sv/common.json
- Fixes for approved reservation tab (seasonal reservation `customer` ui).
- Manual testing: the issues listed in the ticket.
- [TILA-3679](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3679)
[TILA-3679]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: seasonal approved reservations tab

apps/admin-ui/gql/gql-types.ts, apps/admin-ui/src/component/DenyDialog.tsx, apps/admin-ui/src/component/RecurringReservationsView.tsx, apps/admin-ui/src/i18n/messages.ts, apps/admin-ui/src/spa/reservations/[id]/ApprovalButtons.tsx, apps/admin-ui/src/spa/reservations/[id]/ApprovalButtonsRecurring.tsx, apps/admin-ui/src/spa/reservations/[id]/index.tsx, apps/admin-ui/src/spa/reservations/[id]/queries.tsx
-  Add: use series version for mass deny mutations.
- Manual testing: deny reservations (both the single and the series reservations).
- [TILA-3663](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3663)
[TILA-3663]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add: use deny series mass mutation for series

apps/admin-ui/src/spa/my-units/recurring/RecurringReservationForm.tsx, apps/admin-ui/src/spa/reservations/[id]/series/index.tsx
- Fix: empty buffers defaulting to buffers on, so explicitly set the buffer to `0` in mutation.
- Manual testing: series creation / edit should work with and without buffers `admin-ui`
- [TILA-3740](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3740)
[TILA-3740]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: series empty buffers

apps/admin-ui/src/spa/my-units/recurring/RecurringReservationForm.test.tsx, apps/admin-ui/src/spa/my-units/recurring/__test__/mocks.ts
- Fix: admin tests flaking because of a new year.
- Automation: test only change.
- TILA-####
=> fix: tests flaking because of year change

apps/admin-ui/gql/gql-types.ts, apps/admin-ui/src/spa/application-rounds/ApplicationRoundStatusLabel.tsx, apps/admin-ui/src/spa/application-rounds/[id]/review/index.tsx
- Add: sending results for an application-round.
- Fix: label for sent round.
- Fix: remove allocation button for sent round. 
- Manual testing: sending handled application round.
- [TILA-3619](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3619)
[TILA-3619]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add: application round send results

apps/admin-ui/src/spa/application-rounds/[id]/review/index.tsx
- Fix: allocation and send results button order in application-round `admin-ui`.
- Manual testing: reported problem.
- TILA-####
=> fix: allocation button on wrong side

apps/ui/gql/gql-types.ts, apps/ui/pages/reservations/[id]/index.tsx
- Fix: price on single reservation page missing from query so everything looks free.
- Automation: e2e caught the problem.
- TILA-####
=> fix: missing reservation price on single page

packages/common/src/components/BannerNotificationsList.tsx
- Add: paragraph support for banner notifications without adding extra spacing for single paragraph.
- Fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1500
- Manual testing: single line and multi line banner notifications should look normal.
- TILA-####
=> add: support multiline banner notifications

apps/admin-ui/gql/gql-types.ts, apps/admin-ui/src/component/ShowTOS.tsx, apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx, apps/ui/components/Instructions.tsx, apps/ui/gql/gql-types.ts, apps/ui/modules/__tests__/reservation.test.ts, apps/ui/modules/__tests__/reservationUnit.test.ts, packages/common/gql/gql-types.ts, tilavaraus.graphql
- Fix: rich text rendering of all terms
- add: rich text instructions matching https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1474
- Manual testing: check that there are no `<p>` left in admin (create new reservation -> terms) or customer ui (existing reservation instructions).
- TILA-####
=> Fix richtext terms and instructions

apps/admin-ui/gql/gql-types.ts, apps/admin-ui/src/App.tsx, apps/admin-ui/src/spa/reservations/router.tsx
- Fix: restrict url access for reservation edit if user has no edit access to units reservations.
- [TILA-3726](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3726)
- [TILA-3633](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3633)
[TILA-3726]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TILA-3633]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …
=> fix: restrict viewer permission url access

apps/ui/pages/reservation-unit/[id].tsx, packages/common/src/components/form/ControlledSelect.tsx, packages/common/src/reservation-form/MetaFields.tsx, packages/common/src/reservation-form/RadioButtonWithImage.tsx, packages/common/src/reservation-form/ReservationFormField.tsx
- fix: missing reservation form ids (more specific based on what component it is).
- remove unnecessary key attribute from page.
- fix: remove nested input inside button.
- fix: select component search to use front end only filtering
- Automated tests: e2e
- TILA-####
=> fix: missing form ids

apps/ui/components/Accordion.tsx
- Fix: Accordion toggle uses regular `<button>` but was missing the type attribute causing it to submit forms (e.g. applications).
-
- TILA-####
=> fix: accordion toggle submitting forms

apps/admin-ui/src/component/StickyHeader.tsx, apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx, apps/admin-ui/src/spa/reservations/[id]/index.tsx
- fix: sticky button colours after HDS update
- add: testids to `admin` reservation page
-
- TILA-####
=> Fix sticky button colours

apps/admin-ui/gql/gql-types.ts, apps/admin-ui/src/component/EditTimeModal.tsx, apps/admin-ui/src/schemas/reservation.ts, apps/admin-ui/src/spa/my-units/[id]/CreateReservationModal.tsx, apps/admin-ui/src/spa/reservations/[id]/edit.tsx, apps/admin-ui/src/spa/reservations/hooks/index.ts, apps/ui/gql/gql-types.ts, apps/ui/modules/__tests__/reservation.test.ts, apps/ui/modules/queries/reservation.tsx, apps/ui/modules/reservation.ts, apps/ui/pages/reservation-unit/[...params].tsx, apps/ui/pages/reservation-unit/[id].tsx, packages/common/gql/gql-types.ts, tilavaraus.graphql
- update gql types to match core: https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1495
- NOTE: error code change is in https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1635
- Automation: e2e making new reservation / changing existing reservation
- Manual testing: spot testing (esp. edge cases) for new reservations (both sides)
- Manual testing: new series / edit / move / edit series reservations `admin`
- [TILA-3784](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3784)
[TILA-3784]: …
=> Update backend reservation types

apps/admin-ui/src/common/util.ts, apps/admin-ui/src/schemas/reservationMeta.ts, apps/admin-ui/src/spa/my-units/[id]/CreateReservationModal.tsx, apps/admin-ui/src/spa/my-units/recurring/RecurringReservationForm.tsx, apps/admin-ui/src/spa/my-units/recurring/hooks/useCreateRecurringReservation.tsx, apps/admin-ui/src/spa/reservations/[id]/edit.tsx, packages/common/src/conversion.ts, packages/common/src/schemas/schemaCommon.ts
- Fix: untyped metafields transformation breaking create / update mutations `admin`
- Refactor: remove unnecessary meta fields transformation -> use zod form schema and object destructoring. 
- Fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1620
- Automated testing: e2e
- Manual testing: check reservation creation / updates (with form values) `admin`
- TILA-####
=> fix: meta form fields breaking reservation mutation

apps/admin-ui/gql/gql-types.ts, apps/admin-ui/src/component/BufferToggles.tsx, apps/admin-ui/src/component/EditTimeModal.tsx, apps/admin-ui/src/component/ReservationsList.tsx, apps/admin-ui/src/schemas/recurringReservation.ts, apps/admin-ui/src/spa/my-units/[id]/CreateReservationModal.tsx, apps/admin-ui/src/spa/my-units/recurring/RecurringReservationForm.tsx, apps/ui/gql/gql-types.ts, packages/common/gql/gql-types.ts, tilavaraus.graphql
- change to use new mutation to add to series
- requires core: https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1520
- fix: buffer toggles and rename the form keys
- Manual testing: adding new reservation to series.
- Manual testing: moving / creating new reservations with and without buffers.
- TILA-####
=> fix: add reservation to series mutation

apps/admin-ui/src/spa/my-units/[id]/CreateReservationModal.tsx
- fix: invalid enable buffer key after rename in https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1655
-
- TILA-####
=> fix: invalid buffer form key

apps/ui/pages/recurring/[id]/criteria/index.tsx
- Fixes the title and subtitle as designed in figma
- also lines up the NotesWhenApplying box to the right where it should be, even if the criteria content text wouldn't fill enough space on the left to force it there
- Check out the criteria on any application round, the title and subtitle should be correct (and of course the rest of the page, too)
- TILA-3159
=> Application round criteria page fixes

apps/admin-ui/src/spa/applications/[id]/index.tsx
- fix: incorrect status tag translation on application page `admin`
- Manual testing: check different applications have correct Tag translation
- TILA-####
=> fix: incorrect status tag
