.github/workflows/admin-ui.yml
.github/workflows/common-style-test.yml
.github/workflows/ui-e2e.yml
.github/workflows/ui-style-test.yml
.github/workflows/ui-unit-test.yml

Change builds so that we build also when only the dependencies changes (for example when dependabot creates a pr)

Build on dependency changes too

---

ui/pages/reservation-unit/[id].tsx

Linking to #calendar did not work because it is not visible before data is loaded.. scroll in effect instead

TILA-1962 scroll to calendar when hash and data available

---

admin-ui/src/component/reservations/ReservationsTable.tsx
admin-ui/src/component/reservations/queries.ts
admin-ui/src/i18n/messages.ts

- Adds 'createdAt' column for reservation table
- Adds translation for the column header

TILA-2058: Adds 'createdAt' column for reservation table

---

admin-ui/src/common/util.ts
admin-ui/src/component/ReservationUnits/ReservationUnitEditor/SortedSelect.tsx
admin-ui/src/component/my-units/ReservationUnitCalendar.tsx
admin-ui/src/component/my-units/ReservationUnitCalendarView.tsx
admin-ui/src/component/my-units/UnitCalendar.tsx
admin-ui/src/component/my-units/UnitReservations.tsx
admin-ui/src/component/my-units/UnitReservationsView.tsx
admin-ui/src/component/my-units/queries.ts
admin-ui/src/i18n/messages.ts

- Updates events title when the reservation is from another reservationUnit from what is being viewed
- Fixes a bug with the sorting of reservation units when title is undefined
- Fixes a bug with begin date in comparing the events that should be in view

Tila 2046 - ReservationUnits calendar event title

---

common/.gitignore
common/README.md
common/email/convertToHTML.js
common/email/convertToHTML.mjs
common/email/i18n/en.json
common/email/i18n/fi.json
common/email/i18n/sv.json
common/email/templates/partials/closing.mjml
common/email/templates/partials/footer.mjml
common/email/templates/partials/header.mjml
common/email/templates/partials/manageReservation.mjml
common/email/templates/reservationCancellation.template.mjml
common/email/templates/reservationCompleted.template.mjml
common/email/templates/reservationConfirmation.template.mjml
common/email/templates/reservationPreliminary.template.mjml
common/email/templates/reservationRejection.template.mjml
common/email/templates/reservationUpdated.template.mjml
common/email/templates/reservationWaitingPayment.template.mjml
common/email/text-templates/reservationCancellation.template.txt
common/email/text-templates/reservationCompleted.template.txt
common/email/text-templates/reservationConfirmation.template.txt
common/email/text-templates/reservationPreliminary.template.txt
common/email/text-templates/reservationRejection.template.txt
common/email/text-templates/reservationUpdated.template.txt
common/email/text-templates/reservationWaitingPayment.template.txt

Language specific texts moved to i18n-jsons and .mjml to .html conversion updated to replace translation keys using them.
Certain common stuff in the .mjml templates abstracted to partials and couple of variable references fixed with currency formatting pipe added for non-zero prices.
Also added translation of text versions of the email templates in the same way so that these can be generated from the same JSON files as the HTML versions.
Cf. also https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8178106373/Email-pohjat

TILA-2137: translations for email template generation

---

admin-ui/src/component/filters/ReservationStateFilter.tsx

One enum left to use keys instead of values in translatio s.

TILA-2289 Fix missing enum conversion

---

admin-ui/src/common/const.ts
admin-ui/src/component/reservations/RequestedReservations.tsx
admin-ui/src/component/reservations/ReservationsDataLoader.tsx
admin-ui/src/component/reservations/queries.ts

Query time dropped from 1.6s to 350 - 450 ms.
Remove unused query params.
Refactor query into a hook.
Reduce results from 36 to 20.
Fix a type cast error.
Drop useless keys in components.

Fix: speed up loading reservations

---

common/email/i18n/en.json
common/email/i18n/fi.json
common/email/i18n/sv.json
common/email/templates/partials/attributes.mjml
common/email/templates/partials/footer.mjml
common/email/templates/partials/header.mjml
common/email/templates/partials/manageReservation.mjml
common/email/templates/reservationRejection.template.mjml
common/email/text-templates/reservationCompleted.template.txt
common/email/text-templates/reservationConfirmation.template.txt
common/email/text-templates/reservationPreliminary.template.txt
common/email/text-templates/reservationRejection.template.txt
common/email/text-templates/reservationUpdated.template.txt
common/email/text-templates/reservationWaitingPayment.template.txt

- Some typo fixes to texts; manage your reservation should have no separate heading line
- Reservation rejection template should not have the line "thank you for using" in the closing section
- Image columns had zero width on mobile clients because mjml calculates the widths incorrectly below the mobile breakpoint in the generated HTML/CSS if given in pixels; compromising on percentage widths (of the 960px container) yields sufficient results on both mobile and desktop for the Helsinki logo in the header & footer, approximating the desired desktop pixel widths
- Atttributes had line-height fixed to 18px which broke displaying of the salutation line (36px font-size) in Outlook where the top of the line was cropped out; setting it to 1 unit fixed that

TILA-2137: fixes to email templates

---

admin-ui/src/component/ReservationsList.tsx
admin-ui/src/component/my-units/MyUnitRecurringReservation/MyUnitRecurringReservationForm.tsx
admin-ui/src/component/my-units/MyUnitRecurringReservation/RecurringReservationDone.tsx
admin-ui/src/component/my-units/MyUnitRecurringReservation/ReservationsList.test.tsx
admin-ui/src/component/reservations/requested/RecurringReservationsView.tsx
admin-ui/src/component/reservations/requested/RequestedReservation.tsx
admin-ui/src/component/reservations/requested/queries.ts
admin-ui/src/component/reservations/requested/util.ts
admin-ui/src/i18n/messages.ts

The same view as normal requested/reservation but small changes if the reservation is part of a set.
- Different date-time after the header.
- extra Accordion for the other reservations in the set
- update the recurring list styling
Also some fixes to the time format we use.

TILA-2387: Display recurring reservation instead of regular reservation

---

admin-ui/src/component/filters/ReservationUnitFilter.tsx
admin-ui/src/component/filters/queries.ts
admin-ui/src/component/reservations/AllReservations.tsx
admin-ui/src/component/reservations/Filters.tsx

- GQL queries are limited to 100 items (hard limit), so our 400 unit test data got lost, added automatic fetchMore.
- Move reservation unit filter to be always visible in the ui.
- Make only upcoming the default filtering option for all reservations.

TILA-2482: Fix reservation unit filter issues

---

admin-ui/src/common/util.test.ts
admin-ui/src/common/util.ts
admin-ui/src/component/DataTable.tsx
admin-ui/src/component/StickyHeader.tsx
admin-ui/src/component/Tabs.tsx
admin-ui/src/component/applications/Application.tsx
admin-ui/src/component/applications/ApplicationDetails.tsx
admin-ui/src/component/applications/Applications.tsx
admin-ui/src/component/applications/util.ts
admin-ui/src/component/lists/components.tsx
admin-ui/src/component/recurring-reservations/AllApplicationRounds.tsx
admin-ui/src/component/recurring-reservations/ApplicationRoundCard.tsx
admin-ui/src/component/recurring-reservations/Handling.tsx
admin-ui/src/component/recurring-reservations/PreApproval.tsx
admin-ui/src/component/recurring-reservations/Recommendation.tsx
admin-ui/src/component/recurring-reservations/RecommendationsByApplicant.tsx
admin-ui/src/component/recurring-reservations/RecommendationsByReservationUnit.tsx
admin-ui/src/component/recurring-reservations/RecommendedSlot.tsx
admin-ui/src/component/recurring-reservations/ReservationSummariesByReservationUnit.tsx
admin-ui/src/component/recurring-reservations/ResolutionReport.tsx
admin-ui/src/component/recurring-reservations/allocation/ApplicationEventCard.tsx
admin-ui/src/component/recurring-reservations/allocation/ApplicationEventScheduleCard.tsx
admin-ui/src/component/recurring-reservations/review/Filters.tsx
admin-ui/src/component/recurring-reservations/review/Review.tsx
admin-ui/src/component/reservations/Filters.tsx
admin-ui/src/component/withMainMenu.tsx
admin-ui/src/i18n/messages.ts
admin-ui/src/styles/layout.tsx

- Filters: Only show units that are in the round
- Rename: parseDuration  -> formatDuration (object => string)
- Add: Autogrid CSS for Filters (responsive, min 16 rem per filter)
- Sticky header: full screen width (- side nav)
- Responsive fixes to containers with tables (tables overflew at 1360px, top container constrained to 1200px)
- fix i18n plurals
- fix typos and formatting

TILA-2490: bug fixes to Application rounds

---

admin-ui/src/common/const.ts
admin-ui/src/component/Unit/Units.tsx
admin-ui/src/component/Unit/UnitsDataLoader.tsx
admin-ui/src/component/lists/components.tsx
admin-ui/src/component/reservation-units/ReservationUnitsDataLoader.tsx

- Get 50 / 100 elements depending on the page
- Responsive fix for units page
- Always use full container width tables

TILA-2552: fixes to listing pages

---

ui/components/reservation-unit/Address.tsx
ui/public/locales/en/reservationUnit.json
ui/public/locales/fi/reservationUnit.json
ui/public/locales/sv/reservationUnit.json

- adds the accessibility detail link to the reservation unit’s page along with relevant translations for the link text

add: accessibility details link

---

admin-ui/src/common/apolloClient.ts
admin-ui/src/common/const.ts
admin-ui/src/modules/auth/axiosClient.ts
admin-ui/src/pages/_app.tsx
admin-ui/src/pages/api/auth/[...nextauth].ts
admin-ui/src/pages/api/graphql.ts
admin-ui/types/next-auth.d.ts
ui/modules/apolloClient.ts
ui/modules/auth/axiosClient.ts
ui/modules/const.ts
ui/pages/api/auth/[...nextauth].ts
ui/types/next-auth.d.ts

Remove X-Authorization header, because too large headers break graphql endpoint.
Use next backend to redirect the graphql endpoint and remove cookies.
Don't refetch session on tab focus.

TILA-2535: next auth fix broken backend endpoint

---

admin-ui/__mocks__/fileMock.js
admin-ui/src/component/my-units/MyUnitRecurringReservation/MyUnitRecurringReservationForm.tsx
admin-ui/src/component/my-units/MyUnitRecurringReservation/hooks.ts
admin-ui/src/component/my-units/MyUnitRecurringReservation/queries.ts
admin-ui/src/component/reservations/requested/hooks/useCheckCollisions.ts
admin-ui/src/helpers/index.ts

Reuse the single staff reservation logic for recurring reservations, so if either the existing or the new reservation is BLOCKED we don't need to include the buffers in collisions.

TILA-2595: fix don't check buffers for BLOCKED

---

admin-ui/src/common/apolloClient.ts
admin-ui/src/pages/api/graphql/index.ts

Use an api endpoint to create the actual fetch request instead of doing it on the client.
Removes unused cookies and headers when making the request.

TILA-2535: fix (admin): 502 error because of request size

---

admin-ui/src/component/my-units/MyUnitRecurringReservation/MyUnitRecurringReservationForm.tsx
admin-ui/src/component/my-units/MyUnitRecurringReservation/hooks.ts

Recurring reservation form buffer validation against blocked reservation.
Fix: default to blocked when use has made no selection yet.
Fix: check the blocked status from both the reservations in database and the new ones about to be made.

TILA-2595/fix default to type blocked

---

admin-ui/src/component/ReservationsList.tsx
admin-ui/src/component/my-units/MyUnitRecurringReservation/MyUnitRecurringReservationForm.tsx
admin-ui/src/component/my-units/MyUnitRecurringReservation/RecurringReservationDone.tsx
admin-ui/src/component/my-units/MyUnitRecurringReservation/ReservationsList.test.tsx
admin-ui/src/component/my-units/MyUnitRecurringReservation/hooks.ts
admin-ui/src/component/my-units/create-reservation/CreateReservationModal.tsx
admin-ui/src/i18n/messages.ts

Add: staff reservations interval is always either 15 mins or 30 mins.
Fix: converting GQL errors to i18n strings.
Fix: error handling issue (unknown type causing validation error). 
Refs: TILA-2781, TILA-2782

TILA-2781: clamp reservation interval to 30 mins

---

apps/admin-ui/src/common/apolloClient.ts
apps/admin-ui/src/component/ButtonLikeLink.tsx
apps/admin-ui/src/component/PageWrapper.tsx
apps/admin-ui/src/component/Resources/resource-editor/NewResourceModal.tsx
apps/admin-ui/src/component/Spaces/space-editor/SpaceEditor.tsx
apps/admin-ui/src/component/Spaces/space-editor/new-space-modal/Page2.tsx
apps/admin-ui/src/component/notifications/index.tsx
apps/admin-ui/src/component/notifications/page.tsx
apps/admin-ui/src/component/notifications/router.tsx
apps/admin-ui/src/component/reservations/EditTimeModal.tsx
apps/admin-ui/src/component/reservations/requested/ApprovalButtons.tsx
apps/admin-ui/src/component/reservations/requested/ApprovalButtonsRecurring.tsx
apps/admin-ui/src/component/reservations/requested/DenyDialog.tsx
apps/admin-ui/src/helpers/date.ts
apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/schemas/recurringReservation.ts
apps/admin-ui/src/schemas/reservation.ts
apps/admin-ui/src/schemas/schemaCommon.ts
apps/admin-ui/src/styles/util.ts
apps/ui/components/common/PageWrapper.tsx
packages/common/codegen.yml
packages/common/package.json
packages/common/src/common/typography.ts
packages/common/src/components/BannerNotificationsList.tsx
packages/common/src/components/BannerNotificationsQuery.ts
packages/common/types/gql-types.ts
tilavaraus.graphql

Fix: notifications query broken for regular users
Add: Apollo caches for admin notification
Fix: Invalidate admin notifications caches when mutated
Fix: form validation schema (dates + times validation)
Fix: update mutation didn't report errors
Fix: styling and translations based on UI review

TILA-1585: use apollo caches

---

apps/admin-ui/src/component/notifications/page.tsx
apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/schemas/schemaCommon.ts
packages/common/src/common/util.ts
packages/common/src/components/BannerNotificationsList.tsx

Fix: Admin styling: remove extra bracket.
Fix: UI styling: padding around text so the close button doesn't overlap.
Fix: Admin validators: validate html text content length without tags.
Fix: UI: fallback to Fi translation if the actual translation is missing.

TILA-1585: fix notifications validators, styling, lang

---

packages/common/src/components/IconButton.tsx

Now there is no <a> rendered, if the `onClick` attribute returns true, and the href is `javascript:void(0)` (=== the fallback value, aka no `href` was specified).

TILA-2417: IconButton is now a <button>, if there is an onClick but no href given

---

apps/admin-ui/src/component/ReservationUnits/ReservationUnitEditor/ReservationUnitEditor.tsx
apps/admin-ui/src/context/NotificationContext.tsx
apps/admin-ui/src/styles/util.ts

Implemented into the StyledNotification component in styles/utils.ts. Also fixed ReservationUnitEditor.tsx, which was using a custom way for to display notifications, where the vanilla HDS Notification component was in use. It now uses the same StyledNotification which should be used throughout (at least until we unite the notifications of both the ui- and admin-ui sides. There might be some other views which have the same issue.

TILA-2812: Fixes the notification z-index and opacity

---

apps/ui/public/locales/en/common.json
packages/common/src/components/IconButton.tsx

A minimal update to the translation texts, which I missed. Also removed the reference to using `null` in IconButton @params, as its doesn't have a special meaning anymore. (Not that it _actually_ had one earlier either, since I now know that ReactNode accepts both `null` and `undefined` as valid values. 😅)

One word translation update

---

apps/admin-ui/src/component/GlobalElements.tsx
apps/admin-ui/src/component/ReservationUnits/ReservationUnitEditor/ReservationUnitEditor.tsx
apps/admin-ui/src/component/Resources/resource-editor/ResourceEditor.tsx
apps/admin-ui/src/component/Spaces/space-editor/SpaceEditor.tsx
apps/admin-ui/src/component/Unit/SpacesResources.tsx
apps/admin-ui/src/component/Unit/SpacesTable.tsx
apps/admin-ui/src/component/Unit/Unit.tsx
apps/admin-ui/src/context/NotificationContext.tsx
apps/admin-ui/src/styles/util.ts
apps/admin-ui/src/variables.css

Fix autoClose / dismissable toasts that got broken because of previous changes.
Remove unused autoClose override settings.
Remove custom autoClose using a timer (use the one in HDS instead).
All toasts are dismissable.
Success toasts are auto closed, error toasts are not.

fix (admin): notification toast auto close

---

apps/ui/components/reservation-unit/ReservationInfoContainer.tsx
apps/ui/components/reservation/DeleteCancelled.tsx
apps/ui/components/reservation/EditStep0.tsx
apps/ui/components/reservation/ReservationFail.tsx
apps/ui/components/reservations/UnpaidReservationNotification.tsx
apps/ui/pages/reservation/cancel.tsx
apps/ui/pages/reservation/confirmation/[id].tsx
apps/ui/pages/reservations/[...params].tsx
apps/ui/pages/success.tsx
apps/ui/public/locales/en/common.json
apps/ui/public/locales/en/errors.json
apps/ui/public/locales/fi/common.json
apps/ui/public/locales/fi/errors.json
apps/ui/public/locales/sv/common.json
apps/ui/public/locales/sv/errors.json

Use common for errors for now.
Load translations in SSR automatically with next-i18next.

fix: protected route error translations

---

apps/ui/components/single-search/FilterTagList.tsx
apps/ui/components/single-search/SearchForm.tsx

Hides the time related search filters (date/timeBegin, date/timeEnd and duration), as well as the showOnlyAvailable checkbox - as they aren't yet supported by the backend.
Also:
- fixes textSearch showing "undefined" as value on initial pageload
- doesn't show the empty button in the filter tag list, if showOnlyAvailable is the only search parameter (this might be needed for dateBegin in the future too, as it is "on by default" (=== no searches into the past))

Hide time-filters and showOnlyAvailable-checkbox

---

apps/ui/components/common/Navigation/NavigationUserMenu/NavigationUserMenu.tsx

- aligns the navigation dropdown to the button's right edge instead of left
- doesn't touch mobile styles
Ref: TILA-2819

fix: navigation dropdown doesn't go outside the page

---

apps/admin-ui/src/component/recurring-reservations/allocation/index.tsx
apps/admin-ui/src/hooks/usePermission.ts

Filter out units that the user is not supposed to see after the query, these are returned on purpose for other functionaility but should not be displayed in the ui.
Refs: TILA-2507

fix: don't show units without permissions

---

apps/ui/components/application/ApplicationEvent.tsx
apps/ui/components/calendar/ReservationCalendarControls.tsx
apps/ui/components/form/DateRangePicker.tsx
apps/ui/components/reservation-unit/QuickReservation.tsx
apps/ui/components/reservation/EditStep0.tsx
apps/ui/hooks/useOptions.ts
apps/ui/modules/util.ts
apps/ui/pages/reservation-unit/[id].tsx
packages/common/src/calendar/Calendar.tsx
packages/common/src/helpers.ts
packages/common/types/common.ts

- Fix calendar always showing days in Finnish.
- Set the calendar localization to user language (not fi).
- Add type safe conversion function from locale -> what we have translated.

fix: calendar day localization

---

apps/ui/components/reservation/EditStep1.tsx
apps/ui/components/reservation/Step1.tsx

Fixes the old links to generalTerms with the proper href for the terms, as they're now known as boooking and not general

TILA-2933: fix general terms link

---

packages/common/src/reservation-form/MetaFields.tsx

Warnings/validation works like it should, but it was a case where minimum number of participants want's specified. Fixed by making minimum participants 1 if it is not specified, or if it has a value of 0 (as there always needs to be at least one participant).
Ref: TILA-2837

Fix reserving with zero participants

---

apps/ui/components/reservation/ReservationEdit.tsx
apps/ui/components/reservations/UnpaidReservationNotification.tsx
apps/ui/hooks/reservation.tsx
apps/ui/modules/queries/reservation.ts
apps/ui/pages/reservation-unit/[id].tsx
apps/ui/pages/reservations/index.tsx

Checks that `reservation.type` is `ReservationsReservationTypeChoices.Normal` in the listings mentioned in TILA-2893.

TILA-2893: adds type to own reservations gql queries

---

apps/ui/hooks/reservation.tsx
apps/ui/modules/queries/reservation.ts
apps/ui/pages/reservation-unit/[id].tsx
apps/ui/pages/reservations/index.tsx

Because there is no pagination users were shown zero reservations on the frontend when they had a lot of reservations.
Replace frontend filtering with query filters. Every reservation tab has it's own query with it's own query params. Automatically cache tab queries.
Refs: TILA-2893

fix: filter users reservations on backend

---

apps/ui/components/application/Form.tsx
apps/ui/components/application/Page2.tsx
apps/ui/components/application/TimeSelector.tsx
apps/ui/modules/util.ts
packages/common/types/common.ts

Adds handling, styling and aria-fixes to the second page when making recurring reservations. The aria-labels now include the day and time of each slot. The label texts for opening hours are yet to be finalised, but should be added along with the updated legend (now it doesn't contain descriptions for open/not open times, only for the primary and secondary selections).

Adds opening hours to recurring reservation time selection

---

apps/ui/components/calendar/ReservationCalendarControls.tsx

Like elsewhere time should be separated with : not .

fix: use : for time formats

---

apps/admin-ui/src/component/WorkingMemo.tsx
apps/admin-ui/src/i18n/messages.ts

Wasn't checking GraphQL field errors at all so any request that was valid GQL was reported successful to the user, regardless if it was successful in the backend.

fix: check working memo mutation errors

---

apps/admin-ui/src/common/Error404.tsx
apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx

Using an incorrect unit pk param in the url allowed user to move reservation unit to another unit on save.

fix: dont allow moving reservation units

---

apps/ui/components/application/Page2.tsx
packages/common/src/queries/application.ts

Fixes the bug where recurring reservations page 2 showed the wrong available times. It was using the applicationRound pk, when it should have used the reservationUnits pk. This also resulted in one less query, as the needed info could be added to the application query.

Shows the first reservation units schedule on Page2

---

apps/ui/components/single-search/ReservationUnitCard.tsx
apps/ui/public/locales/en/common.json
apps/ui/public/locales/en/reservationUnitCard.json
apps/ui/public/locales/fi/common.json
apps/ui/public/locales/fi/reservationUnitCard.json
apps/ui/public/locales/sv/common.json
apps/ui/public/locales/sv/reservationUnitCard.json

Adds tags about the next possible reservation or lack thereof into search results. Mock data in use, so using `display: hidden` by default so as to not screw up the proper search results, change to `block` to view (originally `inline-flex` but `block` works too).

Reservation unit card status tags

---

apps/admin-ui/src/component/Unit/UnitsTable.tsx
apps/admin-ui/src/component/lists/Tags.tsx
apps/admin-ui/src/component/recurring-reservations/allocation/ApplicationEventCard.tsx
apps/admin-ui/src/component/recurring-reservations/allocation/ApplicationEventScheduleCard.tsx
apps/admin-ui/src/component/recurring-reservations/allocation/ApplicationEvents.tsx
apps/admin-ui/src/component/recurring-reservations/allocation/ApplicationRoundAllocationActions.tsx
apps/admin-ui/src/component/recurring-reservations/allocation/index.tsx
apps/admin-ui/src/component/recurring-reservations/queries.ts
apps/admin-ui/src/component/reservation-units/ReservationUnitsTable.tsx
apps/admin-ui/src/component/reservations/ReservationsTable.tsx
apps/admin-ui/src/component/reservations/requested/util.ts
apps/admin-ui/src/helpers/index.ts
apps/ui/components/application/Form.tsx
apps/ui/components/reservation-unit/Address.tsx
apps/ui/components/reservation/ReservationCancellation.tsx
apps/ui/components/reservation/ReservationInfoCard.tsx
apps/ui/hooks/useReservationUnitList.ts
apps/ui/modules/reservationUnit.ts
apps/ui/modules/util.ts
apps/ui/pages/reservation-unit/[...params].tsx
apps/ui/pages/reservation/confirmation/[id].tsx
apps/ui/pages/reservations/[id]/index.tsx
packages/common/src/calendar/util.ts
packages/common/types/common.ts

- fix: always show all units and reservation-units even if they have no applications
- fix: truncate long reservation-unit names
- fix: tabs overflowing from grid
- refactor: use a common ReservationUnit union type to remove some casts
Refs: TILA-2951

Fix allocation reservation unit selection

---

apps/admin-ui/src/component/Unit/Units.tsx
apps/admin-ui/src/component/Unit/UnitsDataLoader.tsx
apps/admin-ui/src/component/my-units/MyUnits.tsx
apps/admin-ui/src/component/reservations/ReservationsDataLoader.tsx

If we already have data (i.e. the query is in apollo cache) don't show loaders so the user experience is snappier when sorting or moving between pages.

fix: cache table queries when filtering n sorting

---

apps/ui/components/calendar/ReservationCalendarControls.tsx
apps/ui/components/reservation-unit/QuickReservation.tsx
apps/ui/modules/__tests__/reservation.test.ts
apps/ui/modules/reservation.ts
packages/common/src/calendar/util.ts

Makes duration use a H:mm-format string as the value again, instead of a number. Seems to fix booking a time via the calendar, and the quick reservation (w/ price) works, too. However, doesn't yet fix the problems with the calendar showing incorrect reservable times. :/

Changes durationOptions value to "H:mm" format

---

apps/ui/pages/reservation-unit/[id].tsx
packages/common/src/calendar/util.ts

remove: incorrect check (reservationBegins can be null)
add: logging if unit is not reservable
fix: combine two query results (just in case since we are making both)

fix: is reservable

---

apps/ui/components/single-search/SearchForm.tsx
apps/ui/pages/search/single.tsx

The "show only available times" checkbox was checked by default, but the filter wasn't in effect on the initial page load.

Fix: show-only-available checkbox now works on initial page load

---

apps/ui/pages/reservations/index.tsx

- fixes an issue with test automation (more than 100 cancelled).
- cleaner for users since you probably don't care about what you cancelled three years ago.

fix: sort cancelled reservations newest first

---

apps/ui/components/calendar/ReservationCalendarControls.tsx
apps/ui/components/reservation-unit/QuickReservation.tsx
apps/ui/modules/__tests__/reservation.test.ts
apps/ui/modules/reservation.ts
apps/ui/modules/reservationUnit.ts
packages/common/src/calendar/__tests__/calendar.test.ts
packages/common/src/calendar/util.ts

Multi day intervals causing issues for both quick  reservation and the control bar.
- fix: Calendar allowing selecting an extra 30 mins
- fix: 24h time spans working
- fix: QuickReservation next time not working occasionally

Fix quick reservation time intervals

---

apps/ui/components/reservations/UnpaidReservationNotification.tsx
apps/ui/hooks/reservation.tsx
apps/ui/modules/queries/reservation.ts
apps/ui/pages/reservation-unit/[id].tsx
apps/ui/pages/reservations/index.tsx

list reservations query
- make user id mandatory
- is only ment to be used for client reservations

fix: regular user can't see waiting for payment

---

apps/admin-ui/src/component/my-units/DayNavigation.tsx
apps/admin-ui/src/component/my-units/MyUnitRecurringReservation/MyUnitRecurringReservationForm.tsx
apps/admin-ui/src/component/my-units/MyUnitRecurringReservation/generateReservations.ts
apps/admin-ui/src/component/my-units/MyUnitRecurringReservation/hooks.ts
apps/admin-ui/src/component/my-units/create-reservation/CreateReservationModal.tsx
apps/admin-ui/src/component/recurring-reservations/review/AllocatedEventsTable.tsx
apps/admin-ui/src/component/recurring-reservations/review/ApplicationEventsTable.tsx
apps/admin-ui/src/component/reservations/EditTimeModal.tsx
apps/admin-ui/src/component/reservations/requested/util.ts
apps/admin-ui/src/schemas/recurringReservation.ts
apps/admin-ui/src/schemas/schemaCommon.ts
apps/admin-ui/src/spa/ReservationUnit/edit/form.ts
apps/ui/components/application/ApplicationEventSummary.tsx
apps/ui/components/application/Form.tsx
apps/ui/components/form/DateRangePicker.tsx
apps/ui/components/single-search/SearchForm.tsx
apps/ui/modules/util.ts
apps/ui/pages/reservation-unit/[id].tsx
apps/ui/public/locales/en/dateSelector.json
apps/ui/public/locales/en/searchForm.json
apps/ui/public/locales/sv/searchForm.json
packages/common/src/common/util.ts
packages/common/src/components/form/TimeRangePicker.tsx

fix: date picker crashing when the start date is invalid
fix: search page translations
fix: make date utils safe (no throwing)
fix: don't pass undefined to Select input
refactor: remove duplicated date utils
Refs: TILA-2853

Fix data range picker crashing

---

apps/admin-ui/src/component/recurring-reservations/allocation/index.tsx

Large page size -> the tabs overflow from grid container (because max-width > 1200px).
Refs: TILA-2951

fix: allocation tabs overflowing

---

apps/ui/components/application/ApplicationEvent.tsx
apps/ui/components/form/DateRangePicker.tsx
apps/ui/components/form/DateSelectorMenu.tsx
apps/ui/components/form/__tests__/__snapshots__/DateSelectorMenu.test.tsx.snap
apps/ui/components/single-search/SearchForm.tsx
apps/ui/pages/search/single.tsx
apps/ui/public/locales/en/dateSelector.json
apps/ui/public/locales/fi/dateSelector.json
apps/ui/public/locales/sv/dateSelector.json

- fix: search button jumping because tags were removed from dom
- fix: don't send invalid dates to backend (we don't show the user the error, so it only shows empty search results)
- fix: show user an invalid date error if date is not in interval [today, today + 2 years]
- fix: remove all invalid dates when doing a search and reset the picker to empty
- fix: accessible DatePickers in ui
- fix: more comprehensive errors in DateRangePicker
Refs: TILA-3047, TILA-3048

Fix search form date picker errors

---

apps/admin-ui/src/component/ButtonLikeLink.tsx
apps/ui/components/common/ButtonLikeLink.tsx
apps/ui/components/reservation/ReservationCard.tsx
apps/ui/components/search/ReservationUnitCard.tsx
apps/ui/components/single-search/ReservationUnitCard.tsx
apps/ui/modules/queries/reservationUnit.ts
apps/ui/public/locales/en/reservationUnitCard.json
apps/ui/public/locales/en/reservations.json
apps/ui/public/locales/fi/reservationUnitCard.json
apps/ui/public/locales/sv/reservationUnitCard.json
packages/common/styles/buttonCss.ts
packages/common/tsconfig.json

Change the general styling of the cards.
fix: Remove the extra space that got added when moving the mobile tag.
fix: Replace buttons with ButtonLikeLinks where applicable.
fix: Button / Links should span the whole card on mobile
fix: translations
fix: images working when running locally (without image cdn)

fix: search cards too much gap between text

---

apps/ui/components/reservation/ReservationCard.tsx
apps/ui/components/reservation/ReservationOrderStatus.tsx
apps/ui/components/reservation/ReservationStatus.tsx
apps/ui/components/reservation/__tests__/ReservationOrderStatus.test.tsx
apps/ui/components/reservation/__tests__/ReservationStatus.test.tsx
apps/ui/pages/reservations/[id]/index.tsx

Replace only mobile / desktop dom elements with a responsive grid.
Fixes testid="reservation__reservation-info-card__duration"

fix: double test ids on reservation page

---

apps/admin-ui/src/spa/ReservationUnit/edit/form.ts

mutations don't save the values anyway, but the form validation wasn't disabled if the field was disabled by the user.

fix: disabling time should disable it's validation

---

apps/ui/modules/const.ts

Removes 15min and 45min options from seasonal reservation application
Ref: TILA-3020

30min seasonal reservation periods

---

apps/ui/pages/application/[id]/page3.tsx
apps/ui/public/locales/en/application.json
apps/ui/public/locales/sv/application.json

Page 3 was displaying page 4 heading and subheading and non-finnish translations didn't show due to erroneous translation key. Fixed.

fix: page 3 translations

---

.github/workflows/changed-packages.yml
.github/workflows/pipeline.yml
.github/workflows/test-e2e.yml

Node 16 is deprecated in Github.

chore: bump checkout action to v4

---

apps/ui/components/application/Page2.tsx
apps/ui/components/application/TimeSelector.tsx
apps/ui/public/locales/en/application.json
apps/ui/public/locales/fi/application.json
apps/ui/public/locales/sv/application.json

Adds reservation unit selection to a season reservation application, so the user can check opening times of different reservation units. 
Made with a simple useState, as it's meant only for showing the time-slots meant for seasonal bookings and doesn't affect the form contents per se. Some prop drilling necessary, to display the reservation unit selector in the right place.
Also fixes some styling issues on page 2 (legend, reset button..).
Refs: TILA-3052

Adds reservation unit selection to recurring application page2

---

apps/ui/modules/queries/reservation.ts

Two links on reservation page were empty because the field was missing.

fix: empty links on my reservation page

---

apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/ApplicationEventCard.tsx

Incorrectly calculated the number of applied events instead of showing how many times the user requested per week.

fix: incorrect applied count

---

apps/ui/components/application/Page2.tsx

Describe the changes in this pull request here.
- Adds localisation to the reservation unit selection in recurring reservation application page 2
Help your fellow reviewer and write a short description of what's the fastest way to test your changes.
- Make a recurring reservation application, proceed to page 2 and change languages. The reservation unit names in the dropdown should change accordingly.
This pull request resolves all or part of the following ticket(s):
- TILA-3052

Fixes the localisation of reservation unit name selection

---

apps/admin-ui/src/spa/ReservationUnit/edit/form.ts
apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx

- Hides the buffer options from the reservation unit create/edit form
- Create/edit a reservation unit and notice that the section isn't shown
- TILA-3029

comments out buffer options from reservation unit editing for now

---

apps/admin-ui/src/spa/ReservationUnit/edit/form.ts
apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx

- Show buffer options, but hide the block whole day option.
- When editing the reservation unit in admin ui can set buffers, but can't set the block whole days option.
- TILA-####

fix: show buffer options without block whole days

---

apps/ui/components/reservation/EditStep0.tsx
apps/ui/modules/queries/reservation.ts
apps/ui/pages/reservation-unit/[id].tsx

- Fix: extra buffers shown on all new reservations because api value changed from `null` -> `0`.
- Fix: ghost reservation on edit page.
- Fix: show reservation buffers when editing till user changes the time.
- Reservation to Unit without buffer time should not show buffers in calendar either when making a new reservation or changing an existing one.
- Edit page should not show a ghost 30 min reservation for today when landing on the page.
- TILA-####

Fix UI extra buffers

---

apps/admin-ui/src/common/queries.ts
apps/admin-ui/src/hooks/useHandling.ts
apps/admin-ui/src/modules/permissionHelper.ts

- Fix: reduce the number of waiting to be handled shown on the dot (partial).
- Fix: unit permission showing elevated permissions if user had more permissions in another unit.
- Waiting to be handled dot should not show any past reservations anymore.
- Waiting to be handled should not show results for units where the user has no access at all.
- Giving a user unit "view" and "all" permissions to separate units should now hide approval / deny buttons correctly (where user only has "view" access).
- Giving a user unit "reserve" and "all" permissions to separate units should block the user from seeing a reservation (where …

Fix unit permissions getting elevated

---

apps/admin-ui/src/component/QueryParamFilters/ComboboxFilter.tsx
apps/admin-ui/src/component/QueryParamFilters/MultiSelectFilter.tsx
apps/admin-ui/src/component/QueryParamFilters/SearchFilter.tsx
apps/admin-ui/src/component/QueryParamFilters/index.tsx
apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/index.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/AllocatedEventDataLoader.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/ApplicationDataLoader.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/ApplicationEventDataLoader.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/Filters.tsx

- Use directly the url params based on name key.
- Use common translations and paths based on the name.
Requires react-router-dom so can't yet reuse in client application.
- For now only used on allocation and application-round/:id pages so check that the filters work and translations are correct.
- TILA-3169

refactor: add reusable query filter components

---

apps/admin-ui/src/component/my-units/DayNavigation.tsx

- Fix: Sunday first -> Monday first when printing day of week.
- My units Date Picker should show the correct day of week not tomorrow.
- TILA-####

fix: day of week one day ahead

---

apps/ui/components/reservation-unit/Head.tsx
packages/common/src/calendar/util.ts

- Hide QuickReservation and the reservation calendar by adding a `reservationKind === SEASON` check to the isReservationUnitReservable helper function.
- Check out a reservationUnit page, which has reservationKind set to SEASON. The QuickReservation and Calendar elements shouldn't be displayed.
- TILA-3012, TILA-3075

Add checking for SEASON reservationKind to isReservationUnitReservable

---

apps/ui/components/application/TimeSelector.tsx

- Fixes the "Reset calendar"-button `:hover` and `:hover-focus` colors. It inherited some blue styling as a supplementary HDS-button.
- Go to page 2 in the recurring reservation process, select any time slot in the calendar to enable the button. Hover/focus styles are in black.
- TILA-3029

Fix clear calendar button coloring

---

apps/ui/components/common/calendarUtils.ts
apps/ui/components/reservation/EditStep0.tsx
apps/ui/pages/reservation-unit/[id].tsx

- Blocked reservations should show as the reservation unit being closed, so adds a check for `isBlocked` and applies same styling as for when the reservation unit is closed.
- Assumes that we also want to hide the time (and/or other possible text) so sets `color` to `transparent`.
- Create an event/a reservation on the admin side which should be seen as blocked on the client side
- Check the reservation unit's page: the reservation should show as closed
- Same thing for EditStep0 (== edit reservation, first step)
- TILA-3016

fix: show blocked reservations as closed time slots

---

apps/admin-ui/src/component/my-units/ReservationPopupContent.tsx
apps/admin-ui/src/component/my-units/create-reservation/CreateReservationModal.tsx
apps/admin-ui/src/component/reservations/ReservationsDataLoader.tsx
apps/admin-ui/src/component/reservations/ReservationsTable.tsx
apps/admin-ui/src/component/reservations/fragments.ts
apps/admin-ui/src/component/reservations/requested/util.ts
apps/ui/public/locales/fi/application.json

- Adds prefixes to the reservee name, for BEHALF and in special cases STAFF reservations
- Make two reservations of type STAFF:
1. One without supplying any reservee information
2. One with a reservation name or reservee name (..or both)
- Make a reservation of type BEHALF, providing a reservee name
- Check that they are shown correctly in the calendar and the reservations listing:
1. "Sis. |" + reserver/your name, 
2. shows the reservee information you provided, without any prefixes,  and 
3. "Puol. |" + reservee name
- TILA-3023

Fix staff reservation prefix

---

apps/admin-ui/src/common/util.test.ts
apps/admin-ui/src/common/util.ts
apps/admin-ui/src/component/applications/ApplicationDetails.tsx
apps/admin-ui/src/component/reservations/requested/util.test.ts
apps/admin-ui/src/component/reservations/requested/util.ts
apps/admin-ui/src/i18n/index.ts
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/AllocationCard.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/ApplicationEventCard.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/modules/applicationRoundAllocation.ts
apps/ui/components/calendar/ReservationCalendarControls.tsx
apps/ui/components/calendar/ReservationDetails.tsx
apps/ui/components/reservation-unit/Head.tsx
apps/ui/components/reservation-unit/ReservationInfoContainer.tsx
apps/ui/components/reservation/EditStep0.tsx
apps/ui/components/reservation/ReservationInfoCard.tsx
apps/ui/modules/util.ts
apps/ui/pages/reservation-unit/[id].tsx
packages/common/src/calendar/util.ts
packages/common/src/common/util.ts

- Remove extra formatDuration utility function.
- Move formatDuration to common package.
- Fix: pass translation function to formatDuration so next-i18n hook picks up the translations automatically.
- Fix: don't print hours for reservation if they are 0.
- Check reservation and application durations (both admin and client ui's), minutes should be shown only if they !== 0 same with hours.
- TILA-3169

Refactor format duration combine utility functions

---

apps/admin-ui/src/component/my-units/ReservationPopupContent.tsx
apps/admin-ui/src/component/my-units/UnitCalendar.tsx
apps/admin-ui/src/component/my-units/UnitReservations.tsx
apps/admin-ui/src/component/my-units/UnitReservationsView.tsx
apps/admin-ui/src/variables.css

- Add: Sticky times header to the my-units reservation calendar.
- Fix: Popover issues in the same calendar.
- Fix: No vertical scroll when landing on the page, only scroll the Calendar horizontally to the correct time.
-
- TILA-3165, TILA-3170

Add sticky header to my units

---

apps/ui/components/calendar/ReservationCalendarControls.tsx
apps/ui/components/reservation-unit/QuickReservation.tsx
apps/ui/modules/__tests__/reservation.test.ts
apps/ui/modules/reservation.ts
apps/ui/public/locales/en/application.json
apps/ui/public/locales/en/reservationCalendar.json
apps/ui/public/locales/fi/application.json
apps/ui/public/locales/fi/reservationCalendar.json
apps/ui/public/locales/sv/application.json
apps/ui/public/locales/sv/reservationCalendar.json

- Quick reservation used its own set of duplicated translation keys for the field label texts. Changes the referred keys to be the same ones used by the calendar.
- The reset button in the calendar reservation view was styled wrong. Changes it to `secondary` instead of `supplementary` got the basic styling right. Manually fixed the rest.
- Restyles ReservationCalendarControls to make everything fit
- Removes start time input from QuickReservation element, as it was confusing and we list all the available times for the given date anyway right below the input. The user can navigate via the quick reservation time chunks.
- Updates translations for seasonal application unit selection label on Page2
[//]: # "Help your fellow reviewer …

fix: unify the labeling of reservation control fields

---

apps/admin-ui/src/component/reservations/requested/util.ts

- Krista requested that the staff reservation prefix should be used for all staff reservations, for now.
- This PR comments out the reserveeName === reservation.user.name condition
- Make a STAFF-type reservation, and fill in some reservee information
- It should show the "Sis. |"-prefix, even when there is information about the reservee (and in general for all STAFF-type reservations)
- TILA-3023

Use prefix for _all_ STAFF-type reservations

---

apps/ui/components/common/StartApplicationBar.tsx

- Fix: start application link had inverted colours.
- Begin a new application and pick some reservation units, the link should now have white text and transparent background like it used.
- TILA-####

fix: link colours inverted

---

apps/ui/components/calendar/ReservationCalendarControls.tsx
apps/ui/components/reservation-unit/QuickReservation.tsx
apps/ui/components/reservation/EditStep0.tsx
apps/ui/components/reservation/EditStep1.tsx
apps/ui/components/reservation/ReservationCancellation.tsx
apps/ui/components/reservation/ReservationEdit.tsx
apps/ui/components/reservation/Step0.tsx

- Adds `isLoading` status to "Varaa" and "Jatka" buttons in the reservation process, and in reservation edit. Also in the "Peru varaus" button when canceling.
- Go to any reservation unit page and make a reservation. You should see the "Varaa"-button change to a loading spinner once clicked. The same goes for the "Jatka"-buttons in the different steps when making a reservation.
- Once the reservation is made, go to "Omat varaukset" and edit the reservation. The buttons in the edit process should also have loading states.
- Finally: cancel the reservation you just made, and on the cancel page the "Peru varaus"-button …

add: loading states to relevant reservation buttons

---

apps/ui/pages/reservations/index.tsx

- My reservations list shows yesterdays and older reservations (not todays).
- Customer side my reservations list different combinations should never show today in past listing, and should always show today in upcoming even when the time of the reservation is already past.
- TILA-####

fix: remove todays reservastions from past list

---

apps/ui/components/reservation/Step0.tsx
apps/ui/components/reservation/Step1.tsx
apps/ui/components/reservation/styles.ts

- Adds the `isLoading` state to the buttons in the reservation funnel pages. They were accidentally deleted when removing the "Peru"-buttons `isLoading` states on the same pages.
- Same as to the original [PR](#1000), but this time the buttons mentioned above actually have `isLoading` indicators.
- TILA-3160

add: loading states to reservation funnel pages

---

apps/ui/components/single-search/SearchForm.tsx

- Makes the search page duration option interval 30 minutes instead of the 15 it was previously.
- Go to the search page and check out the options for duration. Try to make a search with some duration option selected to make sure the search didn't break.
- TILA-????

fix: remove the 15min interval options from search duration filter

---

apps/ui/components/calendar/ReservationCalendarControls.tsx
apps/ui/pages/reservation-unit/[id].tsx

- Fix: seconds sent through new reservation mutation causing it to always fail when using CalendarControls.
- Fix: permanent loading spinner when failing to create a reservation.
- Try making a new reservation using the CalendarControls (below the reservation calendar), normally it shouldn't fail, but if it does the button should return back to non loading state.
- TILA-####

Fix seconds causing reservation failure

---

apps/admin-ui/src/component/my-units/UnitCalendar.tsx

- Fix: scroll unit reservation calendar to around 7 am (don't show 2am by default). Today is scrolled to earliest possible reservable time (shows some past times also).
- When selecting a day the calendar should start around 7am (it's not very accurate, but it should not be 4am or 10am). Should work on all media sizes (mobile, desktop, tablet) with varying accuracy. 
- [TILA-3212](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3212)
[TILA-3212]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3212?atlOrigin=eyJpIjoiNWRkNTljNzYx …

fix: scroll unit reservation calendar to 7 am

---

apps/ui/components/reservation/ReservationEdit.tsx
apps/ui/modules/queries/applicationRound.ts
apps/ui/modules/reservationUnit.ts
apps/ui/pages/reservation-unit/[id].tsx

- Fix: not showing seasonal times on reservation-unit page.
- Refactor: remove mock times (moved to backend and data generation).
- Check that seasonal reservable times are rendered if the reservation-unit is on an open round, not if it's not.
- [TILA-3214](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3214)
[TILA-3214]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix missing application round info

---

apps/admin-ui/src/component/reservations/EditTimeModal.tsx

- fix: edit time validation missing that admin reservation intervals max out at 30 minutes.
- There should be no validation errors when moving a reservation on admin side (except for 15 and 30 minute intervals which should be translated). All longer intervals default to 30 min validation, same as creating a new reservation.
- TILA-####

fix: remove interval options in edit reservation

---

packages/common/src/reservation-form/ReservationFormField.tsx

- Adds maxLength to reservation input fields, as a quick fix
- The fields in the ticket shouldn't allow longer values than 255 characters.
- The free-of-charge reason field length is not a problem, as it's not limited in the back end
- TILA-3209

fix: set 255 maxLength for the metafields text inputs

---

packages/common/package.json
packages/common/src/browserHelpers.ts
packages/common/src/urlBuilder.ts
pnpm-lock.yaml

- Fix: Django 5 doesn't allow GET request to logout. Replace logout function with dynamic form creation + submit.
- Do logout buttons work in both fronts. Also they should remove Tunnistamo session forcing the next login to go through Tunnistamo.
- TILA-####

fix: django 5 logout is POST not GET

---

packages/common/src/reservation-form/ReservationFormField.tsx

- Fix: don't allow inputing too much text in reservation form because the mutation fails with it.
- Fix: the text areas (regular text input:s were fixed already).
- Quick fix using html maxlength. 
- Submitting a new reservation with any of the forms should no longer fail with backend errors. The text fields are restricted to 255 characters always (the exception of email field which is regex checked).
- [TILA-3209](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3209)
[TILA-3209]: …

fix: limit reservation text areas to 255 chars

---

apps/admin-ui/src/component/my-units/DayNavigation.tsx
apps/admin-ui/src/component/my-units/UnitReservations.tsx
apps/admin-ui/src/component/my-units/UnitReservationsView.tsx
apps/admin-ui/src/component/my-units/create-reservation/CreateReservationModal.tsx
apps/admin-ui/src/component/reservations/EditTimeModal.tsx

- Invalid date can be created with keyboard input, those were not properly handled and the frontend crashed.
- Fix: CreateReservationModal crashing on invalid dates.
- Fix: EditTimeModal crashing on invalid dates.
- Fix: MyUnits calendar crashing on invalid dates.
- All changes are only for the admin frontend (not customer).
- Test creating a new reservation and with an invalid date using the keyboard.
- Test changing a reservation time and with an invalid date using the keyboard.
- Test changing the current date in my-units and with an invalid date using the keyboard.
[//]: # "This pull request resolves all or part of …

Fix time input crashing on keyboard input

---

apps/ui/styles/global.scss

- Fixes page content overflow, causing unnecessary empty space below the footer
- Check frontpage, see that the footer is at the bottom of the page
- TILA-####

fix: page overflowing causing empty space after footer

---

apps/ui/components/application/ReservationUnitList.tsx
apps/ui/components/reservation-unit/ReservationUnitCard.tsx
apps/ui/pages/application/[...params].tsx
apps/ui/pages/search/index.tsx

- fix: selected reservation units not on that application round got incorrectly included when saving the application.
- fix: not any reservation units selected validation error not correctly shown.
- fix: search showing incorrectly selected reservation units after changing application round filter.
- fix: application mobile layout delete and arrow buttons on top of each other.
- refactor: prefer gap over margin-top.
- A new application should never include reservation units not on that application round.
- When selecting different round in the search the count at the bottom of the page should reflect only the …

Fix application saving incorrect units

---

apps/admin-ui/src/component/reservations/ReservationsDataLoader.tsx
apps/admin-ui/src/component/reservations/requested/RequestedReservation.tsx
packages/common/src/reservation-form/ReservationFormField.tsx

- fix: (admin) reservation list first load not showing loader.
- fix: (admin) reservation info text boxes overflowing.
- fix: (ui): email input in reservation form causing a backend error.
- Follow up for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1055
- Follow up for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1044
- [TILA-3209](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3209)
[TILA-3209]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

Fix max length text fields overflowing

---

apps/ui/components/Carousel.tsx
apps/ui/components/common/Modal.tsx
apps/ui/components/reservation-unit/Images.tsx

- adds custom bottom center controls for the image carousel on reservation-unit page
- aria-labels can be localised for the carousel center controls via the controlAriaLabel attribute
- the carousel modal closes only with esc-key, not any keyDown event
- new close-button and a bit of restyling for the image carousel modal
- go to a reservation-unit page which has several images in it, and thus a carousel-element on the right
- inspect the bottom controls (circular small buttons - which are now bigger than before and themed to us)
- the aria-labels on the buttons should be dynamic and localized, so change language and …

fix: Image carousel look and accessibility

---

apps/ui/components/common/SingleLabelInputGroup.tsx
apps/ui/components/form/DateRangePicker.tsx
apps/ui/components/single-search/SearchForm.tsx
apps/ui/pages/reservation-unit/[...params].tsx
packages/common/src/components/form/TimeRangePicker.tsx

- Fixes the accessibility problems in input groups under one label.
- Adds `SingleLabelInputGroup` component, which:
- wraps its `children` in a styled container, which shows them next to each other correctly
- displays a common group label text above them (as defined by `label`)
- visually hides the "proper" label texts from the HDS-component in question, so they can use whatever as their label text and it's decoupled from the group label
- Go to single search page and inspect the inputs which are grouped together (date, time, duration, amount of people)
- They should all have proper a18y (the `for` in the label, …

Search filter label a18y

---

apps/ui/components/reservation-unit/utils.ts
apps/ui/components/reservation/EditStep0.tsx
apps/ui/middleware.ts
apps/ui/modules/__tests__/reservation.test.ts
apps/ui/modules/reservation.ts
apps/ui/modules/reservationUnit.ts
apps/ui/pages/reservation-unit/[id].tsx
packages/common/src/calendar/util.ts

- Fix: min reservation time check failed when generating duration options defaulting to reservation interval.
- Fix: reservation calendar not possible to drag to modify the selected time.
- Fix: webmanifest incorrectly redirected to core for csrf (adding errors in tests).
- Fix: clamp the duration query param (passed from search page) between min / max reservation duration.
- Manual testing: Only normal user app changed. When making new reservations both calendar and quick reservation issues fixed.
- TILA-####

Fix duration options not respecting min duration

---

apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/index.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/Review.tsx
apps/admin-ui/src/styles/layout.tsx

- On application round page the mobile layout broke because of tabs. Use the same solution as in allocation page to clamp the tabs below max window width. 
- Manual check that mobile doesn't overflow on application round page (admin-ui).
- TILA-####

fix: tabs breaking mobile layout

---

apps/admin-ui/src/component/my-units/ReservationUnitCalendar.tsx
apps/admin-ui/src/component/my-units/queries.tsx
apps/admin-ui/src/component/reservations/requested/hooks/index.ts
apps/admin-ui/src/component/reservations/requested/hooks/queries.tsx
apps/admin-ui/src/component/reservations/requested/hooks/useCheckCollisions.ts
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/index.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/Review.tsx

- Fix: recurring reservation moving failed frontend collision checks to other reservations (single version worked). Failing with mutation error when trying instead of showing an error without trying the move.
- Fix: GQL permission error on non admin users from asking for recurringReservation which was unnecessary.
- Fix: remove extra `;` in html after application-round listing table.
- Manual testing of recurring reservations (moving individual reservations should do collision checks properly).
- TILA-####

Fix gql permission errors

---

apps/admin-ui/src/spa/ReservationUnit/edit/form.ts
apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx

- Fix: new reservation unit couldn't be saved because unit pk was missing in the mutation. 
- Manual testing: saving new reservation unit on admin ui.
- TILA-####

fix: can't save new reservation unit

---

apps/admin-ui/src/spa/ReservationUnit/edit/PricingType.tsx

- Fix: edit reservation unit page tax percentage didn't get translated because key's have changed. 
- TILA-####

fix: tax percentage label not translated

---

apps/ui/components/application/ApplicationEvent.tsx
apps/ui/modules/const.ts

- Fix: Reuse of the duration options function broke schedule time: search page is in minutes, schedule in seconds.
- Manual testing: Make a new application schedule (page 1) mutation should work and time should be correctly calculated.
- TILA-####

fix: application schedule incorrect time

---

apps/ui/components/application/ApplicationEventSummary.tsx
apps/ui/components/common/IconWithText.tsx

- Fix: icon + text wrapping weirdly, default to nowrap and add exception to the single case that has long text.
- Manual testing: should fix application modal weird line break.
- TILA-####

fix: application modal text wrapping

---

apps/admin-ui/src/App.tsx
apps/admin-ui/src/common/AuthorizationChecker.tsx
apps/admin-ui/src/common/Error403.tsx
apps/admin-ui/src/common/Error5xx.tsx
apps/admin-ui/src/component/PageWrapper.tsx
apps/admin-ui/src/env.mjs
apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/pages/index.tsx
apps/ui/components/common/Footer.tsx
apps/ui/components/common/PageWrapper.tsx
apps/ui/env.mjs
apps/ui/modules/serverUtils.ts
apps/ui/public/locales/en/footer.json
apps/ui/public/locales/fi/footer.json
apps/ui/public/locales/sv/footer.json

- the url is defined as `EMAIL_VARAAMO_EXT_LINK` env-variable
- implemented in the `Footer` on ui pages
- implemented in 403 & 5xx error pages on admin pages
- reorganise the error texts in the localization files to make link texts more generic
- make 5xx text contents dynamic, as they were hardcoded before
- Check the footer-link on ui side
- Try to access admin pages with invalid credentials, and check the 403 error page
- Induce a 5xx-error to see the link in action on the 5xx-error page
- TILA-3293

fix: updated feedback-page url

---

apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/AllocationCalendar.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/AllocationColumn.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/ApplicationEvents.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/index.tsx
packages/common/types/gql-types.ts
tilavaraus.graphql

- Fix: allocation filtering by preferred order.
- Fix: allocation page calendar and buttons showing allocations that were for a different reservation unit (and allowing removing them).
- Preferred order filter should work as expected.
- Neither the calendar nor the remove / allocate buttons should show application sections that are already allocated in another reservation unit (and not in this one). 
- All filters should be properly applied to the Calendar and Buttons.
- …

Fix preferred order filter

---

apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/spa/applications/[id]/index.tsx
apps/admin-ui/src/spa/applications/queries.tsx
packages/common/src/queries/application.tsx
packages/common/types/gql-types.ts
tilavaraus.graphql

- Add: mass reject buttons to application page.
- Requires: https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1182
- Manual testing: mass reject / return reservation unit options per application. 
- [TILA-3302](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3302)
- [TILA-3300](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3300)
[TILA-3302]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TILA-3300]: …

Add mass reject application options

---

apps/admin-ui/src/component/BirthDate.tsx
apps/admin-ui/src/component/reservations/requested/RequestedReservation.tsx
apps/admin-ui/src/spa/applications/[id]/index.tsx

- Fix: without `can_view_users` permission it was impossible to check the users birthday even though if you can view a reservation or an application you need to be able to check the birthday of the user that made that application / reservation.
- [TILA-3329](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3329)
[TILA-3329]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: non admin users permissions to check birthday

---

apps/admin-ui/src/component/reservations/requested/RecurringReservationsView.tsx

- Canceling a single reservation for recurring reservations should be possible for an ongoing reservation, but not once it's over. Changed the conditions for showing the Cancel-button as specified in the ticket.
- The Cancel-button should be visible for an ongoing reservation, but hidden for already ended ones
- TILA-3253

fix: show cancel button for ongoing (recurring) reservations

---

apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/AllocationCalendar.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/ApplicationEventCard.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/ApplicationEvents.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/index.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/modules/applicationRoundAllocation.ts

- Fix: declined after allocating to this reservation unit was shown under declined, not approved as it should.
- Fix: priority filter not removing suitable times from the Calendar.
- Fix: focus radio button is disabled for rejected sections.
- [TILA-3338](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3338)
[TILA-3338]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix allocation priority filter and bugs

---

apps/ui/hooks/useOptions.ts
apps/ui/pages/search/index.tsx
apps/ui/pages/search/single.tsx

- Fix: search pages (customer side) (both searches) used reservationPurpose instead of purpose.
- Fix: missing sv / en translations from the dropdown selects.
- [TILA-3337](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3337)
[TILA-3337]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: ui search page incorrect purpose options

---

apps/ui/modules/queries/reservationUnit.tsx
apps/ui/pages/reservation-unit/[id].tsx
packages/common/types/gql-types.ts
tilavaraus.graphql

- Switch to using the new `numActiveUserReservations`, which is up to date with active reservations. Corrects the problem where past reservations from today were considered as part of the reservation quota, altho they were in the past.
- Go to a reservation unit (preferrably one with a small maximum reservation quota and minimum reservation time). Make the max amount of reservations with the first one being the next possible reservation. Wait for that first reservation to pass, and note that your reservation quota is accurate, and you can make a new reservation.
[//]: # "This pull request resolves all or part of the …

fix: use active reservations in reservation quota check

---

apps/ui/modules/queries/params.tsx
apps/ui/pages/search/index.tsx
apps/ui/pages/search/single.tsx

- add the toggle to each search so only relevant units are shown in filter
- Units with only seasonal and only direct reservations available aren't shown in single and seasonal searches respectively. In lieu of exhaustively checking every unit a simple test could be to see that the unit lists in the filter should be different on each of the search pages.
- TILA-3247
- TILA-3248

fix: only relevant units are shown in search filter

---

apps/ui/modules/queries/params.tsx
apps/ui/pages/search/index.tsx
apps/ui/pages/search/single.tsx

Reverts City-of-Helsinki/tilavarauspalvelu-ui#1166
Backend queries timeout in production.

Revert "fix: only relevant units are shown in search filter"

---

apps/ui/components/reservation-unit/QuickReservation.tsx
apps/ui/pages/reservation-unit/[id].tsx

- Fix (ui): remove ghost buffers from reservation calendar when no time was selected.
- Fix (ui): show all quick reservation times. 
- Manual testing: reservation process: calendar buffer visibility, quick reservation options.
- TILA-####

Fix quick reservation missing options

---

apps/admin-ui/src/component/my-units/ReservationUnitCalendarView.tsx

- Fix: default reservation unit was shown as selected in input component but it's reservations for it were not shown.
- Manual testing: my-units second tab (single reservation unit) should show reservations without changing the selection from dropdown.
- TILA-####

fix: select default reservation unit in calendar

---

apps/ui/modules/queries/reservation.tsx
apps/ui/pages/reservations/[id]/index.tsx

- Checks that the viewer is the owner of the reservation, so that reservation info can't be viewed by just anyone by typing in the url
- Make a reservation with one user, go to its page and copy the url. Log in as another user and try to view that url.
- TILA-3184

fix: check for correct user when displaying reservation

---

apps/ui/pages/404.tsx
apps/ui/pages/500.tsx
apps/ui/pages/reservations/[id]/index.tsx

- Replace Error403 with SSR check and 404 because Error403 requires a lot of custom code (redirections to custom pages etc.). 
- Add: comments to nextjs error pages.
- Manual testing: changes PR https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1163 (returns 404 page for no access and has no flashes of unauthorised content).
- TILA-XXXX

Replace Error403 with SSR check and not found. 

---

apps/admin-ui/src/component/my-units/ReservationUnitCalendar.tsx
apps/admin-ui/src/component/my-units/UnitCalendar.tsx
apps/admin-ui/src/component/reservations/requested/util.ts

- the staff/behalf prefix was not showing in the calendar entries on the my units page. now they are.
- go to My Units, and make a reservation choosing the staff-option. The calendar entry should show "Sis. |" in front of the reservation name.
- TILA-3171

fix: my units calendar now shows the reservation name with prefix

---

apps/admin-ui/src/hooks/usePermission.ts
apps/admin-ui/src/modules/permissionHelper.ts
apps/admin-ui/src/spa/applications/[id]/index.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/index.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/index.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/queries.tsx

- Add: admin app permission checks for application and application-round pages.
- Refactor: use relay query for application-round.
- Manual testing: application-round, allocation, and application page should correctly return permission error pages if the user doesn't have `can_validate_applications` or `can_handle_applications`.
- [TILA-3206](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3206)
[TILA-3206]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

Add permission checks to application rounds

---

apps/admin-ui/src/component/Unit/UnitsTable.tsx
apps/admin-ui/src/component/Unit/queries.tsx
apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/spa/recurring-reservations/application-rounds/ApplicationRoundCard.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/queries.tsx

- Removes the service sector references and queries
- Replace the -> with a [Näytä ->] button, in the application round card
- Log into the admin view
- Go to "Omat toimipisteet": The table has only "Toimipisteen nimi" and "Varausyksiköitä" columns (service sector is gone)
- Go to "Hakukierrokset": 
- The cards used to have the service sector as the first bit of info, above the application name. It's removed. 
- The link to the application used to be an "->"-icon, but it's now a "Näytä ->" button.
- TILA-3197 
- TILA-3218

Remove service sector

---

apps/ui/components/reservations/UnpaidReservationNotification.tsx
apps/ui/hooks/reservation.tsx
apps/ui/modules/queries/reservation.tsx
apps/ui/public/locales/en/notification.json
apps/ui/public/locales/fi/notification.json
apps/ui/public/locales/sv/notification.json

- shows the time until expiry dynamically (counting down the minutes in the front end, based on the value received in the query on page load)
- adds isLoading text to the cancel-button ("Canceling booking..."), so the button doesn't behave weirdly when in isLoading state (== have only the loading spinner as a label)
- Make a reservation which requires payment, and stop the process without paying. 
- Open two duplicate tabs of the homepage 
- You should see the unpaid reservation notification banner in both of the duplicates.
- Cancel the reservation in one of them - should give you a notification that the reservation …

fix: don't show error in unpaid notification if the time has run out

---

apps/admin-ui/src/i18n/messages.ts

- application section status enum translation not matching the documentation
-
- [TILA-3388](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3388)
[TILA-3388]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: incorrect enum translation

---

apps/ui/modules/reservation.ts
packages/common/src/calendar/util.ts

- Fix: large reservation interval in reservation unit settings causing the `isReservable` check (used when selecting reservation time) incorrectly allowing times that are not reservable.
- Manual testing: selecting a time for new reservation should be more correct (resulting in no / fewer backend errors).
- Should not affect small reservation intervals, should make large intervals behave more correctly (especially if the reservation unit is closed for a small amount of time in the middle of the day).
- …

fix: isReservable check failing with large interval

---

apps/admin-ui/src/spa/applications/[id]/index.tsx

- Fix: rejecting all options moves the Application to `Handled` status, so allow changes even to `Handled` so rejects can be reverted.
- core change https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1199  exposed the bug.
-
- TILA-####

fix: allow rejecting for handled applications

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/component/Unit/UnitsDataLoader.tsx
apps/admin-ui/src/component/Unit/UnitsTable.tsx
apps/admin-ui/src/component/Unit/queries.tsx
apps/admin-ui/src/component/my-units/MyUnitRecurringReservation/__test__/mocks.ts
apps/admin-ui/src/i18n/messages.ts
apps/ui/gql/gql-types.ts
packages/common/gql/gql-types.ts
tilavaraus.graphql

These changes require that this PR 1190 is merged to the backend/core
(https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1190)
- Adds unit group column to UnitsTable
- Go to Omat toimipisteet
- Check that the table has a "Toimipisteryhmä" column
- Both "Varausyksiköitä" and "Toimipisteryhmä" should be sortable columns
- TILA-3217

add: unit group column to Units table

---

apps/ui/pages/reservations/[id]/cancel.tsx

- Bugfix for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1227
- Fix: redirect to reservation instead of returning 404 if it can't be cancelled. 
- Manual testing: `reservation/[id]/cancel` should give 404 when the `id` is invalid, normal page if it can be cancelled, redirect to main reservation page if it can't.
- TILA-####

fix: redirect instead of returning 404 on error

---

apps/admin-ui/src/component/Table.tsx
apps/admin-ui/src/component/Unit/UnitsDataLoader.tsx
apps/admin-ui/src/component/Unit/UnitsTable.tsx

- Bugfix: https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1194
- Fix: tables (especially units / my-units, but others as well like reservation-units) had ghost elements left when sort was changed.
- Fix: more descriptive sort key name.
- Manual testing: same as the original.
- Manual testing: as well test the other admin tables: all should reset cache on data change, i.e. no ghost elements from previous data.
- TILA-####

Fix admin table cache issues

---

apps/ui/components/common/ControlledDateInput.tsx
apps/ui/components/reservation/ReservationInfoCard.tsx
apps/ui/pages/reservation-unit/[...params].tsx
packages/common/src/components/form/ControlledNumberInput.tsx
packages/common/src/components/form/DateTimeInput.tsx
packages/common/src/reservation-form/MetaFields.tsx
packages/common/src/reservation-form/ReservationFormField.tsx

- Fix: navigating to the reservation funnel when reservation is not new returned a 400 error breaking things like "back" button.
- Existing reservations are redirected to the reservation page instead (including `WaitingForPayment`).
- Manual testing: try to break the reservation funnel.
- [TILA-3414](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3414)
[TILA-3414]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix reservation funnel error handling

---

apps/admin-ui/gql/gql-types.ts
apps/ui/gql/gql-types.ts
packages/common/gql/gql-types.ts
packages/common/src/components/BannerNotificationsList.tsx
packages/common/src/components/BannerNotificationsQuery.tsx

- Fix: draft notifications visible in admin ui (core regression), only published with target or all should be shown.
- GraphQL aliases don't work properly with core sql optimisation so use two queries instead.
- Manual testing: notifications should work as production version.
- Core regression in: https://github.com/City-of-Helsinki/tilavarauspalvelu-core/releases/tag/v0.49.0
- TILA-####

fix: draft notifications shown on admin

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/helpers/index.ts
apps/admin-ui/src/i18n/messages.ts
apps/ui/gql/gql-types.ts
packages/common/gql/gql-types.ts
tilavaraus.graphql

- Updates the front to the new application section statuses (removes `FAILED` and `RESERVED`, adds `REJECTED`)
- This code is written using the `application-section-reject-status` branch as backend, and requires it to be merged main in order to function properly: https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1236
- TODO: run codegen to fix merge conflicts, once the backend is up to date (== has merged the PR mentioned above)
- Go to "Haetut vuorot" tab in the application round review view, and note that the status filter is missing the "Epäonnistunut" and "Varattu" options, and has the "Hylätty" option …

fix: application section statuses updated

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/helpers/index.ts
apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/Filters.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/RejectedOccurrencesDataLoader.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/RejectedOccurrencesTable.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/Review.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/utils.ts
apps/ui/gql/gql-types.ts
packages/common/gql/gql-types.ts
packages/eslint-config-custom/react.js
tilavaraus.graphql

- Adds a new tab for rejected occurrences to the application round review view 
- End an application round which results in rejected occurrences for an application, and go view that application
- There should be a "Hylätyt ajankohdat" tab as the last tab on the application review page, next to "Varatut vuorot"
- The table contents (along with links and sortability) should work as specified by the ticket
- The "Hylätyt ajankohdat" tab should be visible for all ended application rounds, and shouldn't be shown otherwise. Hence, viewing an application for an open application round should never show the tab
[//]: # "This …

Add rejected occurrences tab

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/component/reservations/ReservationsTable.tsx
apps/admin-ui/src/component/reservations/fragments.tsx
apps/admin-ui/src/component/reservations/requested/DenyDialog.tsx
apps/admin-ui/src/component/reservations/requested/RequestedReservation.tsx
apps/admin-ui/src/component/reservations/requested/ReservationTitleSection.tsx
apps/admin-ui/src/component/reservations/requested/hooks/index.ts
apps/admin-ui/src/component/reservations/requested/hooks/queries.tsx
apps/ui/components/reservations/UnpaidReservationNotification.tsx
apps/ui/gql/gql-types.ts
apps/ui/modules/queries/reservation.tsx
apps/ui/pages/reservation/confirmation/[id].tsx
apps/ui/pages/reservations/[id]/index.tsx

- Fix: Core: deprecated `order` field in favour of `paymentOrder`
- Automated: Lint.
- Manual testing: payment status should be shown correctly on both ui:s.
- TILA-####

fix: deprecated order field in graphql api

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/component/my-units/MyUnitRecurringReservation/MyUnitRecurringReservationForm.tsx
apps/admin-ui/src/component/my-units/create-reservation/CreateReservationModal.tsx
apps/admin-ui/src/component/reservations/ReservationsDataLoader.tsx
apps/admin-ui/src/component/reservations/queries.tsx
apps/admin-ui/src/hooks/useReservationUnitOptions.tsx
apps/admin-ui/src/hooks/useReservationUnitTypes.tsx
apps/admin-ui/src/hooks/useUnitOptions.tsx
packages/common/src/conversion.ts

- fix: use .tsx extension so gql lint works in the editor
- fix: sort filter options with nameFi when making the query
- fix: reservation type filter not working (missing from query)
- fix: use correct query param type when converting filter parameters (reservations list page)
- Manual testing: unit, reservation unit, reservation unit type comboboxes should have their options sorted by name (admin-ui).
- Manual testing: reservation type filter should work correctly (admin-ui).
- [TILA-3401](https://helsinkisolutionoffice.atlassian.net/browse/TILA …

fix: order filter options and fix reservation type filter

---

apps/admin-ui/src/component/my-units/UnitReservationsView.tsx

- Fix: incorrectly showing date query param as a tag even though it should not be clearable.
- Manual testing: my-units page should not allow clearing the date (selected from the calendar) using the tags, nor should it be shown in them (admin-ui).
- [TILA-3419](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3419) (bugfix)
[TILA-3419]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: my-unit date query param shown in tags

---

apps/admin-ui/gql/gql-types.ts
apps/ui/components/application/ApplicationPage.tsx
apps/ui/components/application/NotesWhenApplying.tsx
apps/ui/gql/gql-types.ts
apps/ui/modules/queries/applicationRound.tsx
apps/ui/pages/criteria/[id].tsx
apps/ui/public/locales/en/applicationRound.json
apps/ui/public/locales/en/reservations.json
apps/ui/public/locales/fi/applicationRound.json
apps/ui/public/locales/sv/applicationRound.json
apps/ui/public/locales/sv/reservations.json
packages/common/gql/gql-types.ts
packages/common/src/queries/application.tsx

- Adds a component which displays the `notesWhenApplying`, translated (defaulting to Finnish), if it's set. If an application round doesn't have any `notesWhenApplying`, nothing is shown.
- Log in to Django (`notesWhenApplying` can't be set elsewhere)
- For an application round (which is open for application), set `notesWhenApplyingFi` and `notesWhenApplyingEn` while leaving `notesWhenApplyingSv` empty.
- Go to "Kausivaraus"
- For the application round in question, behind the "Tutustu hakuohjeisiin"-link there should be a "Huomioi hakiessa" box as per the design.
- Make an application for that same application round, …

add: notes-when-applying component

---

apps/admin-ui/src/common/queries.tsx

- use onlyWithHandlingPermission instead of onlyWithPermission, when determining the application count shown in the orange dot in the main menu, next to "Varaustoiveet"
- The number should now correspond to the correct amount, as specified in the Jira-ticket (TILA-3351)
- TILA-3351

fix: show correct amount of applications in main menu

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/spa/recurring-reservations/application-rounds/queries.tsx

- uses `onlyWithPermissions`-filter in the application round query, so that the user is only shown the application rounds to which they have proper permissions.
- Check that the "Hakukierrokset" listing only shows appropriate application rounds. Probably best done by checking the application round listing as two users with differing permissions.
- TILA-3196

Add onlyWithPermissions-filter to application rounds query

---

apps/admin-ui/src/spa/applications/[id]/index.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/Review.tsx
packages/common/src/apolloUtils.ts

- Fix: if the user has no permission to approve a reservation unit included in the application hide the reject buttons on application page.
- [TILA-3328](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3328)
[TILA-3328]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix permission check deny buttons

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/common/fragments.tsx
apps/admin-ui/src/common/queries.tsx
apps/admin-ui/src/component/reservations/EditPage.test.tsx
apps/admin-ui/src/component/reservations/fragments.tsx
apps/admin-ui/src/context/queries.tsx
apps/admin-ui/src/hooks/usePermission.ts
apps/admin-ui/src/modules/permissionHelper.test.ts
apps/admin-ui/src/modules/permissionHelper.ts
apps/admin-ui/src/spa/applications/[id]/index.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/Review.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/index.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/queries.tsx
apps/ui/components/application/ApplicationPage.tsx
apps/ui/components/application/NotesWhenApplying.tsx
apps/ui/gql/gql-types.ts
apps/ui/modules/queries/applicationRound.tsx
apps/ui/pages/criteria/[id].tsx
apps/ui/public/locales/en/applicationRound.json
apps/ui/public/locales/en/reservations.json
apps/ui/public/locales/fi/applicationRound.json
apps/ui/public/locales/sv/applicationRound.json
apps/ui/public/locales/sv/reservations.json
packages/common/gql/gql-types.ts
packages/common/src/apolloUtils.ts
packages/common/src/queries/application.tsx

- Removes all traces of service sector (and derivatives) from the tilavarauspalvelu-ui codebase.
- Once service sector is removed from the back end, we need to do run `codegen` to remove the references in the auto-generated gql files.
- Do a search for any reference to "serviceSector" in the codebase, and note that all results are from generated files (`tilavaraus.graphql` and various `gql-types.ts`)
- TILA-3389
- TILA-3390

refactor: Remove service sector

---

apps/ui/components/search/SeasonalSearchForm.tsx
apps/ui/components/search/SingleSearchForm.tsx
apps/ui/hooks/useSearchQuery.tsx
apps/ui/hooks/useSearchValues.tsx
apps/ui/modules/search.ts

- Fix: boolean query param incorrectly defaulted to `null` instead of `false` causing toggle to show incorrect value.
- Fix: search pagination breaking: "Show more" button disappears if the query params have not changed and "Search" is pressed again. 
- Manual testing (see Jira).
- [TILA-3496](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3496)
[TILA-3496]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: search page toggle and pagination

---

apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx

- Fix: incorrect condition in disabling preview reservation unit on admin edit page.
- Manual testing: preview button (next to save) should be enabled for all created reservation units (drafts, published etc.) and should go to the public web page (with a query param that bypasses visibility checks).
- [TILA-3429](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3429)
[TILA-3429]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: preview reservation unit link disabled

---

apps/ui/components/common/BreadcrumbWrapper.tsx
packages/common/src/breadcrumb/Breadcrumb.tsx

- Fix: Admin remove double `<a>` from the breadcrumb links. 
- Manual testing: breadcrumb links work in both apps.
- TILA-####

fix: double anchor in breadcrumb

---

apps/admin-ui/src/component/Unit/ReservationUnitCard.tsx
apps/ui/pages/reservations/[id]/index.tsx
packages/common/styles/util.ts

- Fix: reservation subheading date breaking at awkward places.
- Manual testing: style (CSS) change, check the reservation page on mobile / desktop. 
- TILA-####

fix: nowrap reservation subheading date

---

apps/admin-ui/src/component/reservations/requested/util.ts
apps/ui/components/calendar/ReservationCalendarControls.tsx
apps/ui/components/reservation-unit/Head.tsx
apps/ui/components/reservation-unit/QuickReservation.tsx
apps/ui/components/reservation-unit/RelatedUnits.tsx
apps/ui/components/reservation/EditStep0.tsx
apps/ui/components/reservation/ReservationCard.tsx
apps/ui/components/reservation/ReservationInfoCard.tsx
apps/ui/components/search/SingleSearchReservationUnitCard.tsx
apps/ui/modules/__tests__/reservationUnit.test.ts
apps/ui/modules/reservation.ts
apps/ui/modules/reservationUnit.ts
apps/ui/pages/reservation-unit/[...params].tsx
apps/ui/pages/reservation-unit/[id].tsx
apps/ui/pages/reservations/[id]/index.tsx
packages/common/src/reservation-pricing.test.ts
packages/common/src/reservation-pricing.ts

- Fix: don't show price changes that modify VAT before the active date (other price changes are based on the reservation date).
- Refactor: all customer prices include trailing zeros.
- Refactor: price related tests to use `constructInput`
- Fix: CalendarControls price not based on the reservation date (unlike QuickReservation).
- Refactor: remove string comparisons for checking if reservation would be free.
- Refactor: prefer `null` over `undefined` to avoid mistakes.
- Manual testing: shown prices should match the actual prices (i.e. VAT becomes active on the day of purchase, not the day of the reservation).
[//]: # …

Fix VAT change

---

apps/ui/components/reservation-unit/QuickReservation.tsx
apps/ui/components/reservation/EditStep0.tsx
apps/ui/modules/reservationUnit.ts
apps/ui/pages/reservation-unit/[...params].tsx
apps/ui/pages/reservations/[id]/index.tsx

- fix: some isFree booleans inverted after price refactor
- fixes issue: Edit page all times showing disabled.
- fixes issue: can't make paid reservations through the funnel.
- fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1348
- Manual testing: making paid and free reservations and editing them, should work as before.
- TILA-####

fix: price is free boolean inverted

---

apps/admin-ui/src/component/Navigation.tsx
apps/ui/components/common/Navigation.tsx
apps/ui/public/locales/en/navigation.json
apps/ui/public/locales/fi/navigation.json
apps/ui/public/locales/sv/navigation.json
packages/common/src/components/Logo.tsx

- Fixes styling on both admin and client pages as discussed with Oiva:
- extends the blue background to entire screen width
- fixes admin pages mobile layout
- adds correctly styled marker for the active page on client pages
- Makes better use of the inbuilt HDS component's methods in Navigation
- Fixes navigation routes and `isActive` for swedish and english localizations
- Check that both Headers/Navigations work and look as intended, on both client and admin pages
- Also check the mobile functionality/styling, and client pages in Swedish and English localizations
[//]: # "This pull request resolves all or part of the …

fix: navigation styling and function as discussed

---

apps/admin-ui/src/common/urls.ts
apps/admin-ui/src/component/Navigation.tsx
apps/ui/components/common/Navigation.tsx
apps/ui/modules/const.ts

- Fixes the active page check, so that there's an active section for all the pathnames you can end up in
- Check that there's an active section shown in the navigation, e.g. when navigating to a single reservation from the requested reservations page.
- TILA-####

fix: admin-ui navigation active check

---

apps/admin-ui/src/component/Navigation.tsx

- Admin menu button color is now white
- The mobile menu items (== the number in Varaustoiveet) fit the screen
- - doesn’t underline the above mentioned number on hover
- check that the admin-ui header menu fits the screen/looks okay with mobile screen size
- hover the cursor on "Varaustoiveet" (admin-ui): the plain text should be underlined, while the number in the bubble should not
- TILA-####

fix: admin-ui mobile menu styling

---

apps/admin-ui/src/variables.css

- fix: hds mobile nav too small z-index (use the old variable before navigation change).
-
- TILA-####

fix: hds mobile nav z-index

---

apps/admin-ui/src/component/LinkPrev.tsx
apps/admin-ui/src/component/SearchTags.tsx
apps/admin-ui/src/component/reservations/EditPageWrapper.tsx
apps/admin-ui/src/spa/my-units/recurring/RecurringReservation.tsx
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/hooks.ts
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/index.tsx
apps/admin-ui/src/styles/layout.tsx

- Fix: don't pollute navigation history (in allocation pages) when search parameter changes.
- Refactor: back link component.
- Fix: add back link to allocation page that got removed when breadcrumbs was removed.
- Fix: remove sidebar (that was removed) adjustment from application-round page.
- Manual testing: navigation / layout on `admin-ui` allocation / application-round pages.
- TILA-####

Fix admin navigation history

---

apps/admin-ui/src/component/Navigation.tsx
apps/ui/components/common/Navigation.tsx

- Underlines the link text on `:focus` in the header navigation
- Try focusing using the tabulator on the keyboard. The navigation links should show the text underlined when they're focused on.
- TILA-####

fix: show text underline in navigation on focus

---

apps/ui/middleware.ts

- Fix: allow routes to pdf documents without csrf token so webstore can fetch them.
- Manual testing: use `curl` (or similar tool without following redirects / including headers) to fetch the pdf terms and services. Should return the document, not a redirect.
- [TILA-3531](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3531)
[TILA-3531]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: allow pdf access without csrf token

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/modules/permissionHelper.ts
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/review/Review.tsx
apps/ui/gql/gql-types.ts
packages/common/gql/gql-types.ts
tilavaraus.graphql

- Fix: when checking unit access (frontend only check) unit groups were ignored. Caused permission errors on application-round tabs when user didn't have access to all units.
- TILA-####

fix: permission checking units missing unit groups

---

packages/common/src/common/toast.tsx

- Adds a default autoClose time of 5 seconds to all toast messages
- Check that toast messages close by themselves
- The toasts autoClose counter and its visualization (== the shortening "progress bar" at the top) should be paused if the browser window doesn't have focus, likewise when hovering over the message with the mouse pointer
- TILA-####

fix: add a default autoClose time to all toast messages

---

apps/admin-ui/src/component/Navigation.tsx

- force the mobile menu to close when navigating
- Use the header navigation on a mobile screenwidth, see that the menu closes when you navigate
- TILA-3523

hack: close the admin mobile menu when navigating

---

apps/ui/modules/util.ts

- Fix: use `:` as time separator no matter the locale.
-
- TILA-####

fix: use : as hour minute separator in finnish

---

apps/admin-ui/src/common/const.ts
apps/admin-ui/src/spa/recurring-reservations/application-rounds/[id]/allocation/ApplicationEventCard.tsx

- Fix: add unit name (with the reservation unit name) to allocated cards.
- Manual testing: in allocation tool check that cards for already allocated have the unit name also (not just reservation unit), and it's sized reasonably. 
- [TILA-3448](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3448)
[TILA-3448]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: allocation card missing unit name

---

apps/ui/modules/__tests__/reservation.test.ts
apps/ui/modules/reservation.ts
apps/ui/pages/reservations/[id]/index.tsx
apps/ui/public/locales/fi/reservations.json

- Fix: remove extra reason why cancellation is not allowed. (customer ui)
- Manual testing: when looking at an existing reservation there should be correct reason why it can't be moved or cancelled (not two reasons).
- [TILA-3521](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3521)
[TILA-3521]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove double cancellation reasons

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/component/reservations/requested/hooks/index.ts
apps/admin-ui/src/component/reservations/requested/queries.tsx

- fix: order deny reasons by rank (`admin-ui`)
- Manual testing: if rank information is set for deny reasons (in django) they should be ordered correctly when denying a reservations.
- [TILA-3399](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3399)
[TILA-3399]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: order deny reasons by rank

---

apps/admin-ui/src/component/reservation-units/queries.tsx
apps/admin-ui/src/spa/ReservationUnit/edit/queries.tsx
apps/ui/gql/gql-types.ts
apps/ui/modules/__tests__/reservationUnit.test.ts
apps/ui/modules/queries/reservationUnit.tsx
apps/ui/modules/reservationUnit.ts
packages/common/gql/gql-types.ts
tilavaraus.graphql

- Renames reservation unit state properties as per the changes in the backend
- `reservationUnit.state` => `reservationUnit.publishingState`
- `ReservationState`=> `ReservationUnitReservationState`
- requires the back end changes in PR [#1278](https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1278) to work (==not break)
- Everything reservation unit state related should work as it did before the change
- TILA-3473

Update reservationUnit state properties as per backend changes

---

apps/admin-ui/src/common/urls.ts
apps/admin-ui/src/component/ExternalLink.tsx
apps/admin-ui/src/component/Table.tsx
apps/admin-ui/src/spa/application-rounds/[id]/allocation/ApplicationEventCard.tsx
apps/admin-ui/src/spa/application-rounds/[id]/review/AllocatedEventsTable.tsx
apps/admin-ui/src/spa/application-rounds/[id]/review/ApplicationEventsTable.tsx
apps/admin-ui/src/spa/application-rounds/[id]/review/ApplicationsTable.tsx
apps/admin-ui/src/spa/application-rounds/[id]/review/RejectedOccurrencesTable.tsx
apps/admin-ui/src/spa/application-rounds/index.tsx
apps/admin-ui/src/spa/notifications/index.tsx
apps/admin-ui/src/spa/reservation-units/ReservationUnitsTable.tsx
apps/admin-ui/src/spa/reservations/ReservationsTable.tsx
apps/admin-ui/src/spa/unit/ResourcesTable.tsx
apps/admin-ui/src/spa/unit/SpacesTable.tsx
apps/admin-ui/src/spa/unit/UnitsTable.tsx
apps/admin-ui/src/spa/unit/[id]/index.tsx
apps/admin-ui/src/spa/unit/space/Head.tsx
apps/admin-ui/src/styles/util.ts
packages/common/src/termsbox/TermsBox.tsx

- Fix: broken links from url builder change (admin ui).
- Refactor: remove all `a` links (use react-router / next router instead).
- Fix: terms link not respecting user language (customer ui).
- Manual testing: admin ui links should not return 404.
- TILA-####

Fix admin link inconsistency

---

apps/admin-ui/src/common/Error403.tsx
apps/admin-ui/src/component/Navigation.tsx
apps/admin-ui/src/i18n/index.ts
apps/admin-ui/src/pages/auth/logout/index.tsx
apps/ui/pages/auth/logout/index.tsx
packages/common/src/browserHelpers.ts

- Add: redirect to correct apps frontpage after logout when using keycloak.
- Merge with core: https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1323
- Manual testing: with other login / logout changes from keycloak.
- [TILA-3487](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3487)
[TILA-3487]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add: keycloak logout url redirect

---

apps/admin-ui/src/spa/ReservationUnit/edit/tags.tsx
apps/admin-ui/src/spa/application-rounds/ApplicationRoundStatusLabel.tsx
apps/admin-ui/src/spa/notifications/page.tsx
apps/admin-ui/src/spa/reservations/[id]/ReservationTitleSection.tsx
apps/admin-ui/src/spa/unit/[id]/ReservationUnitCard.tsx
apps/ui/components/Carousel.tsx
apps/ui/components/applications/ApplicationCard.tsx
apps/ui/components/applications/ApplicationsGroup.tsx
apps/ui/components/common/Navigation.tsx
apps/ui/components/common/PageWrapper.tsx
apps/ui/components/recurring/ApplicationRoundCard.tsx
apps/ui/components/reservation-unit/RelatedUnits.tsx
apps/ui/components/reservation/ReservationCard.tsx
apps/ui/components/reservation/ReservationOrderStatus.tsx
apps/ui/components/reservation/ReservationStatus.tsx
apps/ui/components/search/ReservationUnitCard.tsx
apps/ui/components/search/SingleSearchReservationUnitCard.tsx
apps/ui/pages/applications.tsx
apps/ui/pages/recurring/index.tsx
apps/ui/pages/reservations/index.tsx
apps/ui/pages/search/index.tsx
apps/ui/pages/search/single.tsx
apps/ui/public/locales/en/reservationUnitCard.json
apps/ui/public/locales/fi/reservationUnitCard.json
apps/ui/public/locales/sv/reservationUnitCard.json
packages/common/src/components/Card.tsx
packages/common/src/components/StatusLabel.tsx
packages/common/src/components/Tag.tsx
packages/common/src/tags.tsx

Adds a `Card` component to common components, which displays a plain card with `heading` and `text`.
It can also display:
- an image (if given an `imageSrc). The image uses `heading`as `alt` text by default, but `imageAlt` allows the use of a any value.
- `infos` (a `value` with an optional `icon` and `testId`)
- `tags` ((== `JSX.Element`s, like `StatusLabel`s and `Tag`s)
- `buttons` (== `JSX.Element`s, like `Button`s, `ButtonLikeLink`s etc)
- child elements, for the moment with the same positioning as `infos`, as our use-cases are mutually exclusive between the two
- if given a `link`, it is used with the image and heading text
- any child elements will be displayed after the main `text`
Use `margin` to apply one on the entire …

Add: universal Card component

---

apps/ui/components/common/ListWithPagination.tsx

- Remove `ui` search page count because it's miss leading to the user as we don't know the total count so it looks like there are no more result.
- Manual testing: search page only thing that should have changed is the count before the list is removed (the one next to load more is still intact).
- TILA-3550

fix: remove search result count

---

apps/admin-ui/src/spa/notifications/index.tsx
apps/admin-ui/src/spa/reservation-units/ReservationUnitsTable.tsx
apps/admin-ui/src/spa/reservations/ReservationsTable.tsx
apps/admin-ui/src/styles/layout.tsx
apps/admin-ui/src/styles/util.ts
packages/common/src/components/Tag.tsx

- Replaces the status-texts with StatusLabel components, within the admin pages tables
- also removes the unnecessary width restriction for the page container
- Go view reservations and/or reservation units in the admin-ui. Their status (+ payment status) should be presented with a status label tag now. Also note that the page content width is now "full-page" (== as wide as the header).
- TILA-3146, TILA-3148, TILA-3149

fix: add status labels to the admin side tables

---

.github/workflows/build-docker.yml
.github/workflows/build.yml
.github/workflows/pipeline.yml
Dockerfile
Dockerfile.final
apps/admin-ui/azure-pipelines-dev.yml
apps/admin-ui/azure-pipelines-release.yml
apps/ui/azure-pipelines-dev.yml
apps/ui/azure-pipelines-release.yml

- Add: docker build action
- Automation: deployment.
- [TILA-3513](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3513)
[TILA-3513]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add: docker build pipeline for ui

---

.github/workflows/build-docker.yml
.github/workflows/build.yml
Dockerfile
package.json

- fix: incorrect base url in `admin-ui` due to it being fixed during build time.
- fix: can't deploy branches to Azure because of incorrect sha.
- fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1416
- Manual testing: deployed `admin-ui` should return html (not 404 errors for `_next` assets).
- [TILA-3513](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3513)
[TILA-3513]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

fix incorrect base url in admin-ui

---

apps/ui/components/reservation/Step0.tsx
apps/ui/pages/reservation-unit/[...params].tsx

- Fix: change trigger validation logic to fire on input instead of onBlur.
- Removes extra tab click / unfocus event required to enable submit button.
- Automation: regression in current E2E test
- TILA-####

fix: trigger reservation form validators on input

---

apps/ui/components/reservation-unit/utils.test.ts
apps/ui/components/reservation-unit/utils.ts

- Fix: find next available times not finding times if there are month long gaps.
- Fix: find next available times sometimes going backwards (find previous time).
- Refactor: unit tests false positive date matches. 
- Manual testing: quick reservation component.
- Automated tests: regression tests for interval find utility.
- [TILA-3530](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3530)
- [TILA-3510](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3510)
[TILA-3530]: …

fix: cant find next available day on next month

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/spa/my-units/recurring/hooks/useCreateRecurringReservation.tsx
apps/admin-ui/src/spa/reservations/[id]/edit.tsx
apps/admin-ui/src/spa/reservations/hooks/hooks.test.tsx
apps/admin-ui/src/spa/reservations/hooks/index.ts
apps/admin-ui/src/spa/reservations/hooks/queries.tsx
apps/ui/gql/gql-types.ts
packages/common/gql/gql-types.ts
tilavaraus.graphql

- Replace frontend N mutations to update a series of reservations with a single mutation.
- Manual testing: changing form values for both series and single reservation should work as before (but faster) `admin-ui`. 
- [TILA-3515](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3515)
[TILA-3515]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

use fast mutation to update reservation series

---

apps/ui/components/reservation/AcceptTerms.tsx
packages/common/src/termsbox/TermsBox.tsx
packages/common/src/termsbox/__tests__/TermsBox.test.tsx

- Fix: warning from nesting `<div>` inside `<p>`
- Automation: p -> Fragment change.
- TILA-####

fix: warning from nesting <div> inside <p>

---

apps/ui/components/reservation/ReservationConfirmation.tsx
apps/ui/pages/reservations/[id]/index.tsx

- Fix: save to calendar link in my reservation not working on other locales than `FI` 
- Manual testing: `Save to Calendar` should work regardless of locale (both after a new reservation and on the reservation page).
- Manually tested on dev because this is not reproducible locally.
- [TILA-3622](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3622)
[TILA-3622]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: calendar link 404 with other locales

---

apps/ui/components/reservation/Step0.tsx

- Fix form validation regression introduced in https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1402
the form was possible to send without setting reserveeType
- Manual testing: new reservation should force the user to pick reservee type.
- TILA-####

fix: submit allowed without reservee type

---

apps/ui/modules/__tests__/reservation.test.ts
apps/ui/modules/reservation.ts
apps/ui/pages/reservations/[id]/index.tsx

- Fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1470
- Fix: not being able to cancel a reservation because incorrectly using old GQL key.
-
- TILA-####

fix: graphql key errors from api change

---

apps/ui/components/reservation-unit/utils.test.ts
apps/ui/components/reservation-unit/utils.ts
apps/ui/components/reservation/EditStep0.tsx
apps/ui/components/reservation/ReservationTimePicker.tsx
apps/ui/gql/gql-types.ts
apps/ui/modules/__tests__/reservable.test.ts
apps/ui/modules/__tests__/reservation.test.ts
apps/ui/modules/__tests__/reservationUnit.test.ts
apps/ui/modules/queries/reservationUnit.tsx
apps/ui/modules/reservable.ts
apps/ui/modules/reservation.ts
apps/ui/modules/reservationUnit.ts
apps/ui/pages/reservation-unit/[id].tsx
apps/ui/pages/reservations/[id]/edit.tsx
apps/ui/test/testUtils.tsx

- Fix: space hierarchy wasn't showing in the customer ui calendar.
- Refactor: dont double query reservations (only affecting is needed for collision checks).
- Refactor: remove GQL object modifications that broke type checking.
- Manual testing: space hierarchy should correctly show in `customer` ui calendars.
- [TILA-3657](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3657)
[TILA-3657]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

fix: include space hierarchy when checking collisions

---

apps/ui/components/common/Sanitize.tsx

- adds all the tags which are usable in the Django rich text editor, to the allowed tags list for the `Sanitizer.tsx`
- Try to use some of the tags which weren't in use before (`h1`-`h6`, `div`, `span`, `ol`, `ul`, `li`, `em`, `u`, `pre`) in the Django editor and check the result (used e.g. in reservation-unit description)
- TILA-3503

Fix: show all richtext tags that are used in Django

---

apps/ui/modules/urls.ts
apps/ui/pages/reservation-unit/[id].tsx

- Fix: continue reservation notification having incorrect link.
- Regression in https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1443
- Manual testing: check that incomplete new reservation can be continued from the notification (ex. close the tab and resume in another tab).
- TILA-####

fix: incorrect continue reservation url

---

apps/ui/components/applications/ApplicationsGroup.tsx
apps/ui/gql/gql-types.ts
apps/ui/modules/queries/application.tsx
packages/common/src/components/Card.tsx

- adds `sentDate` to the applications query
- sorts the items in "omat hakemukset" page based on `sentDate` - within each category respectively
- also: removes the extraneous inline-margin from TagContainer, to line up the status labels with other content properly
- Check that the applications are ordered by their sentDate values (the `sentDate` values for applications can be found in django)
- Check that the tags/statusLabels line up with the content properly (TagContainer shouldn't have any horizontal margins)
- TILA-3572

Order applications based on `application.sentDate` in each category

---

apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx

- Fix: `admin-ui` reservation unit archive double toasting.
- Fix: `admin-ui` reservation unit archive missing translations.
- Fix: `admin-ui` reservation unit archive redirect:n on mutation errors (success behaviour).
- Manual testing: reservation unit archive / save functionality should work correctly. `admin-ui`
- TILA-####

fix: reservation unit archive double toasting

---

apps/ui/components/application/ViewApplication.tsx
apps/ui/components/application/styled.tsx
apps/ui/components/applications/ApplicationCard.tsx
apps/ui/public/locales/fi/applicationCard.json

- fixes status labels styling, categories and translations according to the reported bugs
- the box about receiving a notification when the application is handled is no longer shown when viewing applications that are already handled
- StatusLabel font explicitly weight set to regular, so it doesn't inherit bold from event group heading
- Check on my applications page that the status labels are correct (i.e. they correspond to the heading they're under)
- View an application from the second group, "Käsittelyssä", and note the blue notification box on the bottom labelled "Käsittely"
- That box should not be there when …

Fix observed bugs in applications

---

apps/ui/components/common/ButtonLikeLink.tsx
apps/ui/components/reservation/ReservationConfirmation.tsx
apps/ui/pages/reservations/[id]/index.tsx

- Fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1493
- Fix: don't do prefetch requests on api endpoint calendarUrl. Replaces `next/link` with `<a>` to disable prefetch completely.
- Fix: issue that user language would be set Finnish always on reservation and confirmation pages.
- Manual testing: language saving (other than FI).
- TILA-####

fix: remove prefetch from calendar link

---

apps/admin-ui/src/spa/reservations/[id]/index.tsx

- A reservation's comments label isn't rendered anymore when there was no comment to show
- We now check also for `""`, in addition to `null`-check
- Also includes some code-smell fixes for `spa/reservations/[id]/index.tsx`
- Check out a reservation which doesn't have comments ([example](https://tilavaraus.test.hel.ninja/kasittely/reservations/23413))
- There should not be a "Ratkaisun kommentti:" label without any value on the page
- TILA-3500

Don't show the reservation comments field, if there is no comment

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/hooks/useReservationUnitOptions.tsx
apps/admin-ui/src/hooks/useUnitOptions.tsx
apps/admin-ui/src/spa/reservations/Filters.tsx

- The unit filter and reservation unit filter use the new pageless endpoints when querying for options, so any automatic `fetchMore`s etc are unnecessary even if there's over 100 results
- If any units are selected in the unit-filter, only reservationUnits from the selected units are shown as options in the reservation unit filter.
- The admin page search filters now shows over 100 options if necessary (in practice only unit and reservation unit, but the others are unlikely to have over 100 entries)
- Go to the reservation search in the admin pages (varaustoiveet/kaikki varaukset) and check that the reservation unit …

Show only selected unit reservationUnits as options in admin search filters

---

apps/ui/middleware.ts
apps/ui/pages/applications/index.tsx
apps/ui/pages/reservations/[id]/cancel.tsx
apps/ui/pages/reservations/[id]/confirmation.tsx
apps/ui/pages/reservations/[id]/edit.tsx
apps/ui/pages/reservations/[id]/index.tsx

- Fix: block seeing other users applications in `customer` application (url access) even if the user has access to the data.
- Refactor: replace per page checks from reservations with middleware so any pages under `/reservations` path will always be protected with same rules.
- Manual testing: in the `customer` app users with `admin` (or other roles with access) are blocked seeing other users reservations and applications (similar to regular users) and receive 404 error. This works for all paths related to reservations and applications (i.e. user specific data).
[//]: # "This pull request resolves all or part of the …

Fix check access on page load

---

apps/admin-ui/gql/gql-types.ts
apps/ui/gql/gql-types.ts
apps/ui/modules/__tests__/reservation.test.ts
apps/ui/modules/__tests__/reservationUnit.test.ts
apps/ui/modules/queries/reservation.tsx
apps/ui/modules/reservation.ts
packages/common/gql/gql-types.ts
tilavaraus.graphql

- Update gql types to https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1452
- Automation: lint + e2e tests.
- TILA-####

Update gql types after unused model removal

---

apps/ui/components/common/Sanitize.tsx
apps/ui/components/reservation/ReservationCancellation.tsx
apps/ui/components/reservations/styles.tsx
apps/ui/pages/reservations/[id]/confirmation.tsx
packages/common/src/components/Card.tsx

- Fix: Sanitiser hide old paragraph data extra `<br>`
- Fix: Card max-height so they don't overflow.
- Fix: Reservation page card column (right) overscaling by fixing it's size on desktop.
- Manual testing: fixes to layout changes.
- TILA-####

Fix styling: card height, sanitiser, column sizes

---

apps/admin-ui/.eslintrc.cjs
apps/admin-ui/src/spa/reservations/[id]/Calendar.tsx
packages/common/src/calendar/Toolbar.tsx

- Fix: missing edit reservation time button `admin-ui`
- Fix: lint breaking because naming-convention rule enabled on `admin-ui` 
-
- TILA-####

fix: missing edit time button

---

apps/ui/components/common/Navigation.tsx

- Fix: don't show profile link for ad users (only suomi.fi).
- Manual testing: both ad and suomi.fi users `customer` app, link should be visible only for suomi.fi logins.
- [TILA-3577](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3577)
[TILA-3577]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: dont show profile link if ad user

---

apps/ui/components/application/ApplicantTypeSelector.tsx
apps/ui/components/application/styled.tsx
apps/ui/components/common/Sanitize.tsx
apps/ui/pages/applications/[id]/page3.tsx

- Fix: gap missing on the application info page `page3` causing action buttons on mobile to have no separation from form.
- Fix: rich text overflowing containers (especially problem with long links on mobile).
- Fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1500
- Manual testing: style change, gap should be present.
- Manual testing: long words or links in TOS (or other rich text) should not break responsiveness.
- TILA-####

fix: missing gap on application page 3

---

apps/ui/components/Instructions.tsx
apps/ui/components/reservation-unit/Address.tsx
apps/ui/gql/gql-types.ts
apps/ui/modules/__tests__/reservationUnit.test.ts
apps/ui/modules/reservation.ts
apps/ui/modules/reservationUnit.ts
apps/ui/pages/reservation-unit/[id].tsx
apps/ui/pages/reservations/[id]/cancel.tsx
apps/ui/pages/reservations/[id]/confirmation.tsx
apps/ui/pages/reservations/[id]/edit.tsx
apps/ui/pages/reservations/[id]/index.tsx

- Refactor: use fragments and narrow types for reservation page.
- Refactor: move duplicated Instructions to a separate component.
- Refactor: use a separate query for `reservations/[id]` page. Pages should use their own queries and fragments should be reused for components.
- Fix: redirect `reservations/[id]` page if that reservation is part of an application.
-
- [TILA-3721](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3721)
[TILA-3721]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …

Refactor reservation page and add redirect if part of application

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/spa/applications/queries.tsx
apps/ui/components/AccordionWithIcons.tsx
apps/ui/components/Instructions.tsx
apps/ui/components/application/ApplicantInfoPreview.tsx
apps/ui/components/application/ApplicationEventList.tsx
apps/ui/components/application/ApprovedReservations.tsx
apps/ui/components/application/ViewApplication.tsx
apps/ui/components/reservation-unit/Address.tsx
apps/ui/gql/gql-types.ts
apps/ui/modules/__tests__/reservationUnit.test.ts
apps/ui/modules/queries/application.tsx
apps/ui/modules/reservation.ts
apps/ui/modules/reservationUnit.ts
apps/ui/pages/applications/[id]/view/index.tsx
apps/ui/pages/reservation-unit/[id].tsx
apps/ui/pages/reservations/[id]/cancel.tsx
apps/ui/pages/reservations/[id]/confirmation.tsx
apps/ui/pages/reservations/[id]/edit.tsx
apps/ui/pages/reservations/[id]/index.tsx
packages/common/gql/gql-types.ts
packages/common/src/queries/application.tsx
tilavaraus.graphql

- Add: query params for selected tab / section (so we can link to the section) to application view page. `ui`
- Fix: don't show reservations tab if none of the application section has reservations. `ui`
- Refactor: application queries (move `ui` specific fragments out of `common`).
- Requires: https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1469
- [TILA-3697](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3697)
- [TILA-3703](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3703)
[TILA-3697]: …

Add query param state to application view

---

apps/ui/components/ExternalScripts.tsx

- Fix: cookiehub "Only mandatory cookies" button destroying our cookies including csrftoken leading to all backend requests breaking.
- Manual testing: check that no matter the selection in the cookie consent backend requests don't break. Requires using a frontend query / mutation (not SSR / page load) ex. check your own reservations and switch between tabs.
- Manual testing: confirm it works in production.
- TILA-####

fix: cookiehub destroying csrf token

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/hooks/useOptions.tsx
apps/admin-ui/src/spa/my-units/[id]/hooks/queries.tsx

- Sort reservationPurposes by rank in the admin view
- Client pages have this same change as part of `search-filters-fixes-client` in #1553
- Check from the "Varaustarkoitukset" list that the order corresponds to the one in the "Käyttötarkoitus"-select, when making a reservation. To make sure you can edit some ranks, and see that the changes are reflected in the order of options.
- TILA-3554

Sort reservationPurposes by rank (admin)

---

apps/ui/components/application/Page1.tsx
apps/ui/gql/gql-types.ts
apps/ui/hooks/useOptions.ts
apps/ui/modules/queries/params.tsx
apps/ui/modules/search.ts
apps/ui/pages/index.tsx
packages/common/gql/gql-types.ts
tilavaraus.graphql

- Uses the non-paged endpoints for units and equipment filter options
- Fixes the sorting of options on the search page filters in client view as follows:
- *purpose:* by rank
- *unit:* by name
- *equipments:* by equipments category rank
- *reservation type:* by rank
- Sorts the reservation purpose options by rank, when making a reservation on client side
- Check corresponding name/rank value from Django, and see that the options in respective select-inputs are in the same order on the search page
- Do the same for reservation purposes
- …

Fix dropdown options for client

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/common/apolloClient.ts
apps/admin-ui/src/spa/application-rounds/[id]/review/RejectedOccurrencesDataLoader.tsx
apps/admin-ui/src/spa/application-rounds/[id]/review/RejectedOccurrencesTable.tsx

- Fixes the sorting and pagination of the rejected occurrences listing, shown in a tab under a handled application round which resulted in rejected occurrences
- Sorting by unit name and reservation unit name should now work (along with all the other sorting options)
- Check that the pagination works:
- If you have an application round which has resulted in over 50 rejected occurrences you can test it by viewing that application round
- Otherwise: you need to have an application round which has resulted in at least a few rejected occurrences to be able to test this. To avoid having to create over 50 rejected occurrences …

Fix rejected occurrences tab sorting and pagination

---

apps/admin-ui/src/component/RichTextInput.tsx

- Fix: show paragraphs in `admin` rich text editor so they match the look of `customer` ui.
- Fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1500 sanitised rich text styling.
- Manual testing: CSS change extra line breaks should create huge empty spacing in rich text editor.
- [TILA-3715](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3715)
[TILA-3715]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: show paragraphs in rich text editor

---

packages/common/src/components/Sanitize.tsx

- Fix: remove hiding `<br>` tags in the sanitizer.
- Requires: https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1474 to be merged and run on all servers first. 
- Manual testing: check that there are no unnecessary gaps in text that comes from Django RichText (ex. reservation unit descriptions).
- [TILA-3718](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3718)
[TILA-3718]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …

fix: remove hiding all <br> tags in sanitizer

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/common/queries.tsx
apps/ui/components/Instructions.tsx
apps/ui/components/reservation-unit/Address.tsx
apps/ui/components/reservation-unit/ReservationInfoContainer.tsx
apps/ui/components/reservation/AcceptTerms.tsx
apps/ui/components/reservation/EditStep0.tsx
apps/ui/components/reservation/EditStep1.tsx
apps/ui/components/reservation/ReservationInfoCard.tsx
apps/ui/components/reservation/Step0.tsx
apps/ui/components/reservation/Step1.tsx
apps/ui/components/reservation/SummaryFields.tsx
apps/ui/components/reservations/UnpaidReservationNotification.tsx
apps/ui/gql/gql-types.ts
apps/ui/modules/queries/fragments.tsx
apps/ui/modules/queries/reservation.tsx
apps/ui/modules/queries/reservationUnit.tsx
apps/ui/modules/reservation.ts
apps/ui/pages/reservation-unit/[...params].tsx
apps/ui/pages/reservation-unit/[id].tsx
apps/ui/pages/reservations/[id]/cancel.tsx
apps/ui/pages/reservations/[id]/confirmation.tsx
apps/ui/pages/reservations/[id]/edit.tsx
apps/ui/pages/reservations/[id]/index.tsx
packages/common/gql/gql-types.ts
packages/common/src/queries/fragments.tsx

- Fix: missing tax percentage in ReservationInfoCard. `customer`
- Refactor: all reservation queries to be page specific and use fragments (mostly based on components). `customer`
- Refactor: move queries / fragments to the component / page they are used in.
- Refactor: remove second SSR query from reservation funnel.
- Automation: e2e new / edit / cancel reservation should work as before.
- [TILA-3770](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3770)
[TILA-3770]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3770?atlOrig …

refactor: separate page queries

---

.github/workflows/build-docker.yml
.github/workflows/pipeline.yml
Dockerfile
apps/admin-ui/jest.setup.ts
apps/admin-ui/next.config.mjs
apps/admin-ui/sentry.client.config.ts
apps/admin-ui/sentry.edge.config.ts
apps/admin-ui/sentry.server.config.ts
apps/admin-ui/src/env.mjs
apps/admin-ui/src/instrumentation.ts
apps/admin-ui/src/modules/baseUtils.mjs
apps/admin-ui/src/pages/api/sentry-example-api.js
apps/admin-ui/src/pages/auth/logout/index.tsx
apps/admin-ui/src/pages/healthcheck.tsx
apps/admin-ui/src/pages/index.tsx
apps/admin-ui/src/pages/sentry-example-page.jsx
apps/ui/.gitignore
apps/ui/env.mjs
apps/ui/instrumentation.ts
apps/ui/modules/baseUtils.mjs
apps/ui/modules/serverUtils.ts
apps/ui/next.config.mjs
apps/ui/pages/api/sentry-example-api.ts
apps/ui/pages/sentry-example-page.tsx
apps/ui/sentry.client.config.ts
turbo.json

- add: sentry sourcemap upload to production during build
- add: tunnel
- add: test page / route
- move: sentry upload to Docker build
- remove: the regular build from pipeline (we use docker build)
- fix: build env variables used in CI
- Manual testing: check sentry errors in `stage` / `production` they should include source map information for client side errors.
- [TILA-3631](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3631)
[TILA-3631]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3631?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …

Upload sourcemaps to sentry

---

apps/ui/components/CancellationForm.tsx
apps/ui/pages/reservation/cancel.tsx
apps/ui/pages/reservations/[id]/cancel.tsx

- Fix: cancel single reservation breadcrumb translation key. `ui`
- Add: id (for e2e tests) to cancel reason select.
- Automation: 
- Manual testing: check the cancel page breadcrumb with all languages.
- TILA-####

fix: cancel breadcrumb incorrect translation

---

apps/ui/pages/recurring/index.tsx
apps/ui/public/locales/en/recurringLander.json
apps/ui/public/locales/fi/applicationRound.json
apps/ui/public/locales/fi/recurringLander.json
apps/ui/public/locales/sv/common.json
apps/ui/public/locales/sv/recurringLander.json

- Fixes texts and application round sorting according to the requests in the ticket
- also fixes general Swedish time format ("kl" -> "kl.")
- Check that the texts are correct in all languages, and that the application rounds are shown in requested order
- TILA-3158

Recurring reservations page fixes

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/spa/application-rounds/[id]/review/RejectedOccurrencesDataLoader.tsx

- "Show more"-button now appears and functions as it should in the rejected occurrences tab, on completed application rounds where there are more than 50 items in the list
- Shows total number of rejected occurrences above the listing, as on other tabs
- Check out/make a reservation round which has more than 50 rejected occurrences, and see the respective tab. Check that the "show more" section works like in the other tabs
- TILA-3766

fix: Rejected occurrences tab pagination

---

apps/ui/components/application/ApprovedReservations.tsx

- adds correct values for the heading top/bottom margins on approved reservations page for an application
- removes `gap` from the wrapping `Flex` element, as it's of no use here. The margins for the headings take care of keeping the gaps as wanted.
- Go to the approved reservations tab, in an approved application
- Check that the headings follow the required spacings specified in the [ticket](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3759)
- TILA-3759

fix: approved reservations heading margins

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx
apps/admin-ui/src/spa/ReservationUnit/edit/queries.tsx
apps/ui/modules/search.ts

- Uses alphabetical order for the unit filter options in the search form (client)
- Uses the unpaginated query for equipments in the reservation unit edit page (admin), also fixing the order
- Check out the dropdown-menus mentioned above. Alphabetical order is easy to check, and the reservation unit edit page equipments filter should have the same option order as the one on the search page.
- TILA-3765

fix: Unit filter and equipment filter option orders

---

apps/admin-ui/src/component/RecurringReservationsView.tsx
apps/admin-ui/src/component/ReservationListButton.tsx
apps/admin-ui/src/spa/reservations/[id]/Calendar.tsx
apps/admin-ui/src/spa/reservations/[id]/index.tsx

- fix: selecting single reservation from series shows it in the calendar (and scrolls to calendar)
- fix: update calendar after creating new reservation to series
- Manual testing: show reservation in calendar button should work. `admin` recurring reservation.
- TILA-####

Fix select single reservation side effect

---

apps/admin-ui/src/component/RecurringReservationsView.tsx
apps/admin-ui/src/spa/reservations/[id]/index.tsx

- fix: `reservations` page `admin-ui` spinner overflowing inside an accordion.
- Manual testing: check list of reservations with throttle (the spinner should be normal inside the accordion).
- TILA-####

fix: spinner overflowing inside accordion

---

apps/admin-ui/src/spa/unit/space/ParentSelector.tsx
apps/admin-ui/src/spa/unit/space/SpaceEditor.tsx
apps/admin-ui/src/spa/unit/space/new-space-modal/NewSpaceModal.tsx

- Fix: user can save a space without selecting a parent, but selecting top level (ghost) parent fails the mutation.
- Manual testing: check saving both new and old space (moving parents) `admin`
- [TILA-3820](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3820)
[TILA-3820]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: cant save new top level space
